from pathlib import Path
import html,json,re,xml.etree.ElementTree as ET
ROOT=Path.cwd();OUT=ROOT/'outputs'
def p(s):return '<p>'+s+'</p>'
def pre(s,kind=''):return '<pre'+(' data-language="'+kind+'"' if kind else '')+'><code>'+html.escape(s)+'</code></pre>'
def table(head,rows):return '<div class="reference-table"><table><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def sec(id,title,body):return '<section><h2 id="'+id+'">'+title+'</h2>'+body+'</section>'
def link(f,l,a=''):return '<a href="'+f+'.html'+('#'+a if a else '')+'">'+l+'</a>'
def figure(id,title,boxes,edges,caption):
 h=max(b[1]+b[3] for b in boxes)+35
 s=f'<figure class="concept-figure"><svg viewBox="0 0 900 {h}" role="img" aria-labelledby="{id}-title {id}-desc" xmlns="http://www.w3.org/2000/svg"><title id="{id}-title">{title}</title><desc id="{id}-desc">{caption}</desc><defs><marker id="{id}-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="#477b9e"/></marker></defs>'
 for a,b,c,d in edges:s+=f'<path d="M{a} {b} L{c} {d}" class="svg-link" marker-end="url(#{id}-arrow)"/>'
 for x,y,w,z,t,n in boxes:s+=f'<rect x="{x}" y="{y}" width="{w}" height="{z}" rx="9" class="svg-node"/><text x="{x+14}" y="{y+25}" class="svg-text">{html.escape(t)}</text><text x="{x+14}" y="{y+48}" class="svg-note">{html.escape(n)}</text>'
 return s+'</svg><figcaption>'+caption+'</figcaption></figure>'
def sequence(id,title,events,caption):
 h=100+len(events)*56
 s=f'<figure class="concept-figure"><svg viewBox="0 0 900 {h}" role="img" aria-labelledby="{id}-title" xmlns="http://www.w3.org/2000/svg"><title id="{id}-title">{title}</title><defs><marker id="{id}-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="#477b9e"/></marker></defs><text x="85" y="30" class="svg-title">客户端 Client</text><text x="690" y="30" class="svg-title">服务器 Server</text><path d="M150 50 V{h-20} M750 50 V{h-20}" class="svg-dash"/>'
 for i,(d,t) in enumerate(events):
  y=88+i*56;a,b=(150,750) if d=='>' else (750,150)
  s+=f'<text x="450" y="{y-12}" text-anchor="middle" class="svg-text">{html.escape(t)}</text><path d="M{a} {y} H{b}" class="svg-link" marker-end="url(#{id}-arrow)"/>'
 return s+'</svg><figcaption>'+caption+'</figcaption></figure>'
pages=[]
def page(f,t,g,sections,source,nexts):
 common=sec('reading','阅读位置与版本',p('上级：'+(link('standard-library-overview','标准文库') if f=='standard-part-7-2' else link('standard-part-7-2','第 7-2 部分：ACSI'))+'。按“概念 → 属性与服务 → SCD 证据 → 工程使用”阅读。')+p('标准基线：DL/T 860.72—2004（等同 IEC 61850-7-2:2003）；参考 SCD 为 SCL 2007 B4。抽象模型、协议映射、XML 配置和设备运行值分别解释。本文为原创导读，工程摘录保留源文件关键字与名称，不是完整可投产配置。'))
 sources=sec('sources','来源与继续阅读',p('原文定位：'+source.rstrip('。')+'。参考文件：860[1].7-2.pdf（123 个 PDF 页），南雷变2026041614.scd。PDF 页指文件顺序页；正文印刷页通常为 PDF 页减 5。')+p('原 PDF：D:/IEC61850/IEC61850标准[中文.完整版]/860[1].7-2.pdf。本站离线阅读不依赖原 PDF 目录。')+p('继续阅读：'+' · '.join(link(a,b) for a,b in nexts)))
 content='<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+t+'｜IEC 61850 离线知识库</title><link rel="stylesheet" href="../assets/style.css"></head><body><header class="top"><div class="chapter"><p class="section-kicker">'+g+' · 第 7-2 部分专题</p><h1>'+t+'</h1><p>从信息对象，理解服务、配置引用和运行行为。</p></div></header><main class="chapter">'+common+'\n'+'\n'.join(sections)+sources+'</main><footer class="footer">IEC 61850 离线知识库 · 标准、映射、工程配置与运行证据分别核对</footer><script src="../assets/navigation.js"></script></body></html>\n'
 (OUT/'chapters'/f'{f}.html').write_text(content,encoding='utf-8');pages.append((f,t,g))
ABBR=[
('AA','Application Association','应用关联','关联模型','通信双方及其访问上下文；包括 TPAA、MCAA。','acsi-server-associations','association'),
('ACSI','Abstract Communication Service Interface','抽象通信服务接口','接口体系','定义对象、服务及行为；描述功能用 ACSI，描述线上编码进入 SCSM。','acsi-abstraction','two-abstractions'),
('BRCB','Buffered Report Control Block','缓存报告控制块','模型类','按触发组织并缓存报告事件；恢复时核对 EntryID、溢出与保留范围。','acsi-runtime-models','report'),
('CDC','Common Data Class','公用数据类','数据类','规定共用属性结构，如 DPC、SPS、MV；SCD DOType@cdc 表达类别。','acsi-runtime-models','data'),
('DAType','Data Attribute Type','数据属性类型','类型名','ACSI 泛指属性类型；SCL DAType/BDA 描述结构属性，叶子用 bType。','acsi-common-types','basic'),
('DataRef','Data Reference','数据引用','属性名','DATA 完整路径，如 C_G1101XLD0/LLN0.FunEna1；没有同名 SCL 标签。','acsi-common-types','references'),
('dchg','Data Change','数据变化','触发选项','值按 CDC 规则变化时触发，测量还需考虑死区；DA 特征和控制块采用选项分层。','acsi-common-types','triggers'),
('dupd','Data Update','数据刷新','触发选项','属性刷新可触发，值不必不同；不等于周期完整性报告。','acsi-common-types','triggers'),
('FC','Functional Constraint','功能约束','访问分类','按用途筛选 DA，如 ST、MX、CO、SV、SG、SE；不等于操作授权。','acsi-runtime-models','fc'),
('FCD','Functionally Constrained Data','功能约束数据','引用形式','DO 与 FC 的组合，选择此 DO 在该 FC 下的属性集合；FCDA 省略 daName 可表达 FCD。','acsi-runtime-models','dataset'),
('FCDA','Functionally Constrained Data Attribute','功能约束数据属性','引用形式 / XML 元素','属性与 FC 的组合；SCL FCDA 也能表达 FCD，按 doName/daName/fc 区分。','scd-acsi-evidence','goose-evidence'),
('GI','General Interrogation','总召唤','运行命令','客户请求当前数据集完整快照；TrgOps.gi 是选项，运行 GI=true 才是启动。','acsi-runtime-models','report'),
('intgPd','Integrity Period','完整性周期','属性名','单位 ms；ACSI 通常写 IntgPd，XML 写 intgPd；0 不产生周期完整性报告。','acsi-common-types','triggers'),
('LCB','Log Control Block','日志控制块','模型类','决定哪些数据按何种触发写入 LOG；LogControl 是配置，不包含历史条目。','acsi-runtime-models','log'),
('qchg','Quality Change','品质变化','触发选项','品质变化可触发，即使数值不变；DA@qchg 与 TrgOps@qchg 分层。','acsi-common-types','triggers'),
('SBO','Select Before Operate','操作前选择','控制模型','先选择再操作；普通安全用 Select，增强安全用 SelectWithValue，并受超时约束。','acsi-runtime-models','control'),
('SCL','Substation Configuration Language','变电站配置语言','工程语言','XML 工程交换语言；SCD 是文件类型，服务请求和响应不写成 SCD 标签。','scd-acsi-evidence','positions'),
('SG','Setting Group','定值组','参数集合 / FC','共同切换的一组参数；FC=SG 为激活视图，FC=SE 为编辑视图。','acsi-runtime-models','settings'),
('SGCB','Setting Group Control Block','定值组控制块','模型类','管理组数、激活、编辑和确认；LLN0/SettingControl 表达工程配置。','acsi-runtime-models','settings'),
('TrgOp','Trigger Option','触发选项','属性特征','属性事件能力；控制块 TrgOps 选择采用哪些事件；DA 的 dchg 不证明报告已使能。','acsi-common-types','triggers'),
('URCB','Unbuffered Report Control Block','非缓存报告控制块','模型类','连接期间尽力报告；不按 BRCB 方式补送断线期间事件。','acsi-runtime-models','report'),
('TPAA','Two Party Application Association','双边应用关联','模型类','双向、面向连接；Associate 建立，Release 正常释放，Abort 异常中止。','acsi-server-associations','tpaa'),
('MCAA','Multicast Application Association','多路广播应用关联','模型类','发布者向一个或多个订户单向发送无确认信息；不逐个订户执行 Associate。','acsi-server-associations','mcaa'),
('SCSM','Specific Communication Service Mapping','特定通信服务映射','映射规范','将抽象类和服务映射到具体寻址、协议与编码，如 8-1、9-2。','acsi-abstraction','interfaces'),
('EntryID','Entry Identifier','条目标识符','公共类型','报告恢复和日志查询使用的不透明字节串；不是业务编号或时间。','acsi-common-types','entry'),
('EntryTime','Entry Time','条目时间','公共类型','报告、日志与通信子系统的条目相关时间；表示由 SCSM 定义。','acsi-common-types','entry'),
('TimeStamp','Time Stamp','时标','公共类型','由纪元秒、秒的小数、时间品质组成；可表示分辨率不证明设备准确度。','acsi-common-types','timestamp'),
('PACKED-LIST','Packed List','压缩表','公共类型','有序分量的紧凑编码，不能通过该类型独立访问分量；不是文件压缩。','acsi-common-types','packed')]
classes=[
('SERVER','服务器','6','ServiceAccessPoint、LogicalDevice、File、TPAppAssociation、MCAppAssociation','外部可见行为；发现 LD 与文件','AccessPoint/Server'),
('TPAA','双边应用关联','7.4','AssociationId、AuthenticationParameter','建立、释放、中止客户/服务器关联','Authentication 与 DynAssociation 是配置/能力线索；关联实例在运行时'),
('MCAA','多路广播应用关联','7.5','AuthenticationParameter','GOOSE、GSSE、多播 SV 的单向上下文','发布控制块及 Communication 地址；无 MCAA 标签'),
('LOGICAL-DEVICE / LD','逻辑设备','8','LDName、LDRef、LogicalNode','功能 LN 的容器，也可用于代理/网关','Server/LDevice@inst'),
('LOGICAL-NODE / LN','逻辑节点','9','LNName、LNRef、Data、DataSet、控制块、Log','组织功能数据及信息交换对象','LN0/LN，lnType 引用 LNodeType'),
('DATA','数据','10','DataName、DataRef、Presence、DataAttributeType、FC、TrgOp、CDC 组成','应用信息，如 Pos、PhV','LNodeType/DO → DOType；DOI/SDI 为实例设置'),
('DAType / DataAttribute','属性类型与属性','10.2.2.4','DATName、DATRef、Presence、CompositeComponent、PrimitiveComponent','递归属性结构及基本类型叶子','DOType/DA → DAType/BDA；DAI 为实例值'),
('DATA-SET / DS','数据集','11','DSName、DSRef、DSMemberRef[1..n]','有序成员引用，组织读写与发布','LN0 或 LN 下 DataSet/FCDA'),
('SETTING-GROUP-CONTROL-BLOCK / SGCB','定值组控制块','13','SGCBName、SGCBRef、NumOfSG、ActSG、EditSG、CnfEdit、LActTm','定值组编辑、确认和激活','LN0/SettingControl'),
('BUFFERED-REPORT-CONTROL-BLOCK / BRCB','缓存报告控制块','14.2.2','名称/引用、RptID、RptEna、DatSet、ConfRev、OptFlds、BufTm、SqNum、TrgOps、IntgPd、GI、PurgeBuf、EntryID、TimeOfEntry','事件报告与缓冲重同步','ReportControl@buffered=true'),
('UNBUFFERED-REPORT-CONTROL-BLOCK / URCB','非缓存报告控制块','14.2.4','名称/引用、RptID、RptEna、Resv、DatSet、ConfRev、OptFlds、BufTm、SqNum、TrgOps、IntgPd、GI','连接期间报告与客户保留','ReportControl@buffered=false'),
('LOG-CONTROL-BLOCK / LCB','日志控制块','14.3.2','LCBName、LCBRef、LCBEna、DatSet、OptFlds、TrgOp、IntgPd、LogRef','按触发记录数据集','LogControl；抽象 LCBEna 与工程 logEna 分开'),
('LOG','日志','14.3.3','LogName、LogRef、OldEntr、NewEntr、OldEntrTm、NewEntrTm、Entry','历史存储与条目查询','Log 表达存储配置，条目由服务查询'),
('GOOSE-CONTROL-BLOCK / GoCB','GOOSE 控制块','15.2','GoCBName、GoCBRef、GoEna、AppID、DatSet、ConfRev、NdsCom','组织 GOOSE 发布','LN0/GSEControl@type=GOOSE'),
('GSSE-CONTROL-BLOCK / GsCB','GSSE 控制块','15.3','GsCBName、GsCBRef、GsEna、AppID、DataLabel、LSentData','早期固定状态集合发布','GSEControl@type=GSSE；本 SCD 未观察到'),
('MULTICAST-SAMPLED-VALUE-CONTROL-BLOCK / MSVCB','多播采样控制块','16.2','MsvCBNam、MsvCBRef、SvEna、MsvID、DatSet、ConfRev、SmpRate、OptFlds','MCAA 连续样本发布','LN0/SampledValueControl 多播配置'),
('UNICAST-SAMPLED-VALUE-CONTROL-BLOCK / USVCB','单播采样控制块','16.3','UsvCBNam、UsvCBRef、SvEna、Resv、UsvID、DatSet、ConfRev、SmpRate、OptFlds','经 TPAA 向保留客户传输；关联结束停止','SampledValueControl@multicast=false；参考文件未显式配置 false'),
('FILE','文件','20','FileName、FileSize、LastModified','非结构化二进制存储与传输','Services/FileHandling 能力；没有完整目录 XML')]
coverage=[('1～4','范围、引用、定义与缩略语','standard-part-7-2','scope'),('引言、5.1～5.4','两层抽象、基本模型与服务分类','acsi-abstraction','two-abstractions'),('5.5','基本类型和公共类型','acsi-common-types','basic'),('6','服务器与目录服务','acsi-server-associations','server'),('7','关联、访问视窗、TPAA/MCAA','acsi-server-associations','access-view'),('8～10','LD、LN、DATA、DAType、FC 和读写','acsi-runtime-models','data'),('11～12','数据集及取代','acsi-runtime-models','dataset'),('13','定值组','acsi-runtime-models','settings'),('14','报告与日志','acsi-runtime-models','report'),('15','GOOSE 与 GSSE','acsi-runtime-models','gse'),('16','多播/单播采样与格式','acsi-runtime-models','sampled-values'),('17','控制、预约操作与原因诊断','acsi-runtime-models','control'),('18','时间与同步','acsi-engineering-workflows','time'),('19','命名、引用和作用域','acsi-common-types','references'),('20','文件传输','acsi-engineering-workflows','files'),('附录 A','基本/模型/服务一致性声明','acsi-engineering-workflows','conformance')]
page('standard-part-7-2','第 7-2 部分：抽象通信服务接口 ACSI','标准文库',[
sec('scope','1. 本部分解决什么问题',p('监控计算机读取设备数据、接收事件或提出控制请求时，需要约定“访问哪个对象、调用什么服务、结果是什么意思”。ACSI 给出这一共同约定。SERVER 是 IED 对外呈现的模型和行为，不一定是一台独立计算机；Client 是请求服务并接收通知的应用。一次设备通过传感、控制或执行装置与信息系统相连，不能把断路器直接当作网络服务器。类 Class 是共同规则，实例 Instance 是具体对象，二者不能混用。')+table(['部分','职责','阅读'],[('7-1','建模原理和应用/设备/通信视图',link('standard-part-7-1','原理与模型')),('7-2','类、公共类型、服务及行为','本章'),('7-3 / 7-4','CDC 属性结构 / LN 与数据语义',link('data-attributes-reference','数据与 CDC')),('6','SCL 配置及工程交换',link('standard-part-6-scl','SCL')),('8-1 / 9-1 / 9-2','具体通信服务映射 SCSM',link('service-mapping','服务映射')),('附录 A','设备支持的 ACSI 角色、模型和服务',link('acsi-engineering-workflows','一致性声明','conformance'))])+p('本章总结所给早期版本，不宣称覆盖后续全部版次。规范性引用和参考文献是继续核对模型与映射的入口，不能用本站导读替代正式条文。')),
sec('model','2. 基本模型与层级',figure('hierarchy','SERVER 到 DA 的包含与引用',[(30,20,390,70,'SERVER','外部可见行为和服务入口'),(30,120,390,70,'LOGICAL-DEVICE / LD','一组功能的容器'),(30,220,390,70,'LOGICAL-NODE / LN','LLN0、MMXU1、XCBR1 等'),(30,320,390,70,'DATA / DO','Pos；复合 DATA 可继续包含子数据'),(30,420,390,70,'DataAttribute / DA → 分量','stVal、q、t；或 cVal.mag.f'),(490,220,370,70,'DataSet / 控制块 / LOG','与 DATA 同属 LN 的组成'),(490,330,370,70,'控制块 → DataSet','引用有序成员清单'),(490,430,370,70,'DataSet → FCD / FCDA','引用数据，不复制其定义')],[(225,90,225,120),(225,190,225,220),(225,290,225,320),(225,390,225,420),(420,255,490,255),(675,290,675,330),(675,400,675,430),(490,465,420,465)],'左侧为基本包含层级；右侧为 LN 内数据集、控制块、日志以及已标明的引用方向。')+p('基本骨架是 SERVER → LD → LN → DATA，DA 再描述数值、品质、时标及配置等细节。DataSet 组织交换成员，控制块组织交换行为。Control 针对可控 DATA；Control Block 则管理报告、日志、定值或发布过程。')),
sec('models','3. ACSI 类与支撑类型完整导览',p('下表覆盖参考正文的对象类及第 10 章属性类型结构。Control、Substitution、Time/TimeSynchronisation 是行为/服务模型，没有同名 SCL 元素。SimpleCDC、CompositeCDC 是 DATA 特例化；CompositeComponent、PrimitiveComponent 是 DAType 组成角色，具体 CDC 和属性类型在 7-3 定义。')+table(['类 / 类型','中文','章节','组成属性','功能 / 场景','SCD 表现'],classes)),
sec('uses','4. 高频模型的用途',table(['模型','概念 / 功能','使用场景','详解'],[('DataSet','有序引用已有数据','批量读写、报告、日志、GOOSE/SV',link('acsi-runtime-models','数据集','dataset')),('Substitution','以指定值和品质替代过程来源','数据源异常时按工程规则取代；与测试区分',link('acsi-runtime-models','取代','substitution')),('Control Block','管理使能、引用、选项和状态','配置报告/记录/切换/发布',link('control-blocks-reference','控制块属性')),('Control','请求执行应用动作','开关、设点、分接头',link('acsi-runtime-models','控制','control')),('Time / TimeSynchronisation','统一 UTC 语义与品质','事件排序、预约动作、采样协作',link('acsi-engineering-workflows','时间','time')),('File Transfer','传输与管理字节文件','读取扰动记录或受支持配置',link('acsi-engineering-workflows','文件','files'))])),
sec('abbreviations','5. 缩略语、属性名和类型名',p('这些名称已同步进入全局术语检索。表中区分缩略语、属性名和类型名，保留必要英文原文。')+table(['名称','英文','中文','类别','功能与用法'],[(a,b,c,d,e+' '+link(f,'详解',z)) for a,b,c,d,e,f,z in ABBR])),
sec('coverage','6. 原文章节覆盖清单',table(['原文','知识范围','本站位置'],[(a,b,link(c,'打开专题',d)) for a,b,c,d in coverage])+p('建议顺序：'+link('acsi-abstraction','抽象接口')+' → '+link('acsi-common-types','公共类型')+' → '+link('acsi-server-associations','服务器与关联')+' → '+link('acsi-runtime-models','运行模型')+' → '+link('scd-acsi-evidence','真实 SCD 对照')+' → '+link('acsi-engineering-workflows','工程核查')+'。全服务名称继续查阅 '+link('acsi-services','ACSI 服务分类与功能全表')+'。'))],
'引言、1～20 章、规范性附录 A 及参考文献；覆盖指原创知识总结和关联阅读，不是逐条替代正文。',[('acsi-abstraction','两层抽象'),('acsi-common-types','公共类型')])
page('acsi-abstraction','抽象接口：信息模型与通信协作','技术知识',[
sec('two-abstractions','1. ACSI 的两层抽象',p('引言中“两种含义”说的是 ACSI 的抽象，不是两个英文全称。第一层将设备表现为网络可见、可访问的信息模型；第二层定义设备交换信息的概念性协作，具体协议实现放到 SCSM。抽象并非省略功能细节，而是让共同结构与行为独立于内部硬件和协议栈。')+table(['层次','抽象对象','仍然定义的内容','使用时机'],[('设备信息抽象','内部变量、硬件和接线实现','LD/LN/DATA/DA 的层级、语义、类型与属性','描述断路器位置用 XCBR.Pos 及 stVal/q/t，不需要知道寄存器地址'),('通信协作抽象','协议栈、操作系统与线上编码','请求、成功/失败响应、通知及行为条件','描述 GetDataValues、Report、Operate；具体编码再查 8-1 等')])+figure('abstract','ACSI 与模型、配置、映射',[(40,20,810,70,'实际功能与设备','传感、计算、保护或执行'),(40,130,810,70,'信息抽象：7-2 + 7-3 + 7-4','框架 + CDC + LN/DO 语义'),(40,240,390,70,'通信协作：ACSI','GetDataValues / Report / Operate'),(470,240,380,70,'工程表达：SCL / SCD','配置实例、类型、引用和订阅'),(40,350,810,70,'具体实现：SCSM 与设备','8-1 / 9-2 等完成寻址和通信编码')],[(445,90,445,130),(220,200,220,240),(650,200,650,240),(220,310,220,350),(650,310,650,350)],'对象模型与服务共同约束互操作，工程文件表达配置，映射规范定义具体通信。')),
sec('interfaces','2. 抽象接口种类与使用时机',table(['接口族','典型服务','功能 / 条件','具体实现要核对'],[('发现与自描述','GetServerDirectory、GetDataDefinition','发现可访问对象及其结构','服务映射、访问视窗与目录范围'),('数据读写','Get/SetDataValues、Get/SetDataSetValues','读当前信息；设置允许写的属性','FC、类型、状态及权限'),('报告与日志','Report、Get/SetBRCBValues、QueryLogByTime','接收异步事件或检索历史','报告保留、缓存、触发和条目范围'),('控制','Select、SelectWithValue、Operate、CommandTermination','按状态机提出动作请求','ctlModel、超时、检查、结果反馈'),('对等事件发布','SendGOOSEMessage、SendGSSEMessage','向订户单向发布','控制块、成员、地址、重发及接受策略'),('采样值发布','SendMSVMessage、SendUSVMessage','按采样节奏传输样本','成员表示、计数、采样率和同步'),('关联、时间、文件','Associate/Release/Abort、TimeSynchronisation、GetFile','访问上下文、时间协作与文件获取','认证、实际对时机制、文件能力')])+p('说“读取一个测量值”时，应先定位模型和 FC，再说明 ACSI 服务及结果语义，最后解释 MMS 映射。说以太网类型、地址或 BER 字节时已经进入映射层。抽象服务名也不保证厂商 SDK 有一个同名函数。')),
sec('example','3. 用测量值串起四个层面',p('原创教学对象 LD_A/MMXU1.PhV.phsA.cVal.mag.f，FC=MX：模型说明它是电压数值分量，单位和品质要沿 CDC 读取；GetDataValues 说明怎样访问；SCD 类型链说明它在哪个模板定义；SCSM 说明请求如何编码。当前数值和通信结果需要运行证据。')+table(['层面','问题','能说明的内容'],[('模型','是什么','MMXU、PhV、WYE/CMV、结构与 FLOAT32 叶子'),('服务','怎样访问','引用、FC、请求和响应'),('配置','在哪里定义','LN@lnType → LNodeType/DO → DOType/DA → DAType/BDA'),('应用','是否可用','还需 q、t、单位、来源、模式与工程规则')]))],
'引言注 1、第 1 章、第 5 章及 6～20 章。',[('acsi-common-types','类型与命名'),('acsi-server-associations','访问与关联')])
BASIC=[('BOOLEAN','false / true','二值状态、使能与选项','BOOLEAN'),('INT8','−128～127','8 位有符号整数','INT8'),('INT16','−32768～32767','16 位有符号整数','INT16'),('INT24','−8388608～8388607','24 位有符号；原文时间表也引用此名','按 XML 与映射核对'),('INT32','−2147483648～2147483647','32 位有符号整数','INT32'),('INT128','−2^127～2^127−1','128 位有符号，计数器等使用','INT128'),('INT8U','0～255','8 位无符号','INT8U'),('INT16U','0～65535','16 位无符号','INT16U'),('INT24U','0～16777215','24 位无符号','INT24U'),('INT32U','0～4294967295','32 位无符号，周期/计数等','INT32U'),('FLOAT32','IEEE 754 单精度','通常有效精度约 7 位十进制；不代表传感器精度','FLOAT32'),('FLOAT64','IEEE 754 双精度','通常有效精度约 15～16 位十进制','FLOAT64'),('ENUMERATED','采用类型时定义有序值集','原文允许用户扩展，需声明语义来源','Enum + EnumType/EnumVal@ord'),('CODED ENUM','采用类型时定义有序编码集','原文不允许用户扩展，映射紧凑编码','如 Dbpos 等具体类型，不能机械写 CODED ENUM'),('OCTET STRING','采用类型时定义最大长度','不透明字节串','Octet64 等具体 SCL 类型'),('VISIBLE STRING','采用类型时定义最大字符数','可见字符；ObjectName32、ObjectReference255','VisString32 / VisString255 等'),('UNICODE STRING','采用类型时定义最大字符数','多语言字符串','Unicode255 等')]
ERRORS=[('instance-not-available','实例不可用','对象不存在或当前视窗不可用'),('instance-in-use','实例正在使用','所需空闲对象已在使用'),('access-violation','访问违例','客户不具有访问资格'),('access-not-allowed-in-current-state','当前状态不允许访问','例如使能时限制配置写入'),('parameter-value-inappropriate','参数值不合适','单个参数不满足要求'),('parameter-value-inconsistent','参数值不一致','参数间或与配置不一致'),('class-not-supported','类不支持','服务器不支持请求的类'),('instance-locked-by-other-client','被其他客户锁定','关联保留或选择冲突'),('control-must-be-selected','控制必须先选择','SBO 未获得有效选择资格'),('type-conflict','类型冲突','值类型与定义不同'),('failed-due-to-communications-constraint','通信约束导致失败','通信资源或传输限制'),('failed-due-to-server-constraint','服务器约束导致失败','服务器资源或实现限制')]
page('acsi-common-types','ACSI 基本类型、公共类型与对象引用','数据模型',[
sec('basic','1. 基本类型全表与 DAType',p('5.5.2 表 2 列出以下 17 种类型。范围属于 ACSI 基线；SCL bType 集合和线上编码由各自规范确定，本表不是 XML 模式或报文长度表。浮点特殊值的使用还受 CDC/设备约束。')+table(['类型','值域','功能与特点','SCD 表达线索'],BASIC)+p('第 10 章的 DAType 结构具有 DATName（ObjectName）、DATRef（ObjectReference）、Presence（BOOLEAN），以及 CompositeComponent[0..n] 或 PrimitiveComponent[0..1]；组成不能同时为空，可递归如 cVal → mag → f。SCL DA@bType="Struct" 引用 DAType@id，BDA 可继续引用结构，叶子用 bType；枚举引用 EnumType。模板 ID 是文件内部标识，不是运行对象路径。')),
sec('common','2. 八项公共类型与采用位置',table(['类型 / 属性名','类型与域','功能 / 时机','样式 / SCD 关系'],[('ObjectName','VISIBLE STRING32','在同一父容器内唯一命名','FunEna1、dsRelayEna；由 name/inst 等字段体现'),('ObjectReference','VISIBLE STRING255','完整路径定位实例','C_G1101XLD0/LLN0.FunEna1；由多项 XML 属性重建'),('ServiceError','ENUMERATED；12 项基础错误','否定服务响应','Response−{ServiceError=access-violation}；非 SCD 运行日志'),('EntryID','任意八位位组串；语法/语义由 SCSM 定义','报告恢复和日志查询','教学字节串 01 A2 00 10；非时间/业务编号'),('PACKED-LIST','采用处定义的有序分量','整体紧凑编码','TriggerConditions 的 BOOLEAN 分量；XML 可拆成命名属性'),('TimeStamp','纪元秒 + 秒分数 + 时间品质','CDC 时标及指定采用处','DA@bType=Timestamp；实例 t'),('EntryTime','SCSM 定义的日期和时间','报告/日志与通信条目时间','TimeOfEntry、TimeOfLog；不要求与 TimeStamp 同编码'),('TriggerConditions','PACKED-LIST；五项 BOOLEAN','触发或条目包含原因','TrgOps 配置与 DA 事件特征分层')])+p('这里的属性名是抽象表字段，不保证 SCD 存在同名 XML 属性。XML 值域、默认值与存在条件按 SCL 版本核对。')),
sec('references','3. 对象名、对象引用与语法',pre('ObjectName       = 单个层级实例名\nObjectReference  = LDName/LNName[.Name[...]]\nLDRef            = LDName\nLNRef            = LDName/LNName\nDataRef          = LDName/LNName.DataName[.DataName[...]]\nDARef            = DataRef.DataAttributeName[.DAComponentName[...]]\nDSRef（永久）    = LDName/LNName.DataSetName\nDSRef（关联专用）= @DataSetName\nSGCBRef          = LDName/LLN0.SGCB\nGoCBRef          = LDName/LLN0.GoCBName')+p('“/”分隔 LD 与 LN，“.”分隔后续层级。方括号表示可选，省略号表示递归，均不是实际对象名字符。可有多个子 DATA、一个顶层 DA 和多个属性分量，引用大小写须保持一致。访问 LD 本身用 LDRef，不强行补 /LN。')+table(['字段 / 规则','基线约束','例子 / 边界'],[('ObjectName','最多 32 个可见字符，父容器内唯一','Pos 是名；LD_A/XCBR1.Pos 是引用'),('ObjectReference','最多 255 个可见字符','抽象路径不含 FC；FC 单独限定'),('LDName','第 19 章最多 32 字符，应用特定','LDevice@inst=LD0 不等于完整 LD 名；通常由 IED 名和 inst 构成，ldName 等按实际版本规则'),('LNName','前缀 + 四字符类名 + 数字实例号；基线前缀与实例号合计≤7','GO + GGIO + 1 → GOGGIO1；LLN0 为管理 LN'),('DataName','第 19 章最多 10 字符，7-4 数据名','不能把这一基线限制当作所有后续版/扩展的全规则'),('FCD 名称部分','基线最多 29 字符，含点分隔符，不含 FC','与完整 ObjectReference 长度是不同约束'),('名称字符','A～Z、a～z、0～9、下划线','/、.、@ 用于路径/作用域，不是任意局部名字符'),('DSRef','永久路径或 @DataSetName','非永久实例属于创建它的关联'),('控制块引用','BRCB/URCB/LCB 为 LD/LN.控制块名','MMS 映射 LLN0$BR$brcbRelayEna01 与抽象点路径分开'),('作用域','第 19.3 节服务器、LD、TPAA 使用 /、LDName/、@ 标志','是作用域规则，不合并为一种 DO 路径')])+p('真实例子：C_M1101X 的 MEAS 数据集成员 prefix=GO、lnClass=GGIO、lnInst=1、doName=AnIn1、daName=mag.f、fc=MX。按通常命名得到 <code>C_M1101XMEAS/GOGGIO1.AnIn1.mag.f</code>，FC=MX 单独保留。MMS 可能映射为域名及带 $ 的项目名，不给 ACSI 点路径夹入 $MX$。')+p('原文表 42 将 LOG 引用写为 LDName/LDName，与同文 LOG 属性及工程表达不宜机械拼接。本文保留来源差异提示；实际 LogName/LogRef 按采用的 SCSM 和设备目录核对，LogControl@name 不能直接代替日志存储实例名。')),
sec('errors','4. ServiceError：全部十二项基础错误',p('属性名 ServiceError，类型 ENUMERATED，用于否定响应。下列场景为原创解释，不表示每项只有一种原因。表 5 没有给出跨映射通用数字编码，不能自行分配 MMS 错误码。')+table(['枚举','中文','典型解释'],ERRORS)+p('第 17 章 AddCause 另提供控制原因；SCSM 及其应用层也可以扩展表示。基础服务错误、控制原因与协议实际字段分别核对。本次错误不会由 SCD 配置文件记录。')),
sec('packed','5. PACKED-LIST：整体的有序分量',p('采用处定义有序类型分量，再映射为高效编码。原文规定不能通过该类型单独访问其中某一值；理解上可拆解，访问粒度按服务/映射确定。它不是 ZIP 压缩算法。位数和位序由采用处及映射定义。')+table(['采用处','逻辑组成','配置 / 运行表现'],[('TriggerConditions','dchg、qchg、dupd、integrity、GI','TrgOps 命名 BOOLEAN 属性'),('TimeQuality','闰秒、时钟故障、未同步、准确度','时标内部品质，通常不拆成 SCD 标签'),('Check','synchrocheck、interlock-check','控制请求参数，非 SCD 命令'),('OptFlds','报告/采样模型规定的字段选择','OptFields / SmvOpts 为配置，不证明相同线上位序')])),
sec('timestamp','6. TimeStamp：语法、精度和时间品质',p('TimeStamp 使用 1970-01-01 00:00:00 UTC 纪元。原表 7 写 SecondSinceEpoch=INT32、FractionOfSecond=INT24；语义是非负纪元秒和 24 位二进制小数，不可按普通有符号整数解释分数最高位。线上无符号表示、宽度、位布局和闰秒处理由映射确定。')+table(['分量','原文类型 / 存在','值域与含义','例子'],[('SecondSinceEpoch','INT32 / M；原表 0～MAX','整秒数；MAX 按采用规范/映射核对','1 为纪元后 1 秒'),('FractionOfSecond','INT24 / M','Σ bᵢ×2⁻⁽ⁱ⁺¹⁾，i=0..23；0≤分数&lt;1','1000…0 → 0.5 s；8388608/2²⁴'),('TimeQuality','TimeQuality / M','产生时标的时源品质','时间可读不代表已同步')])+pre('教学演算：SecondSinceEpoch=1，FractionOfSecond=0.5\nUTC 显示：1970-01-01T00:00:01.500Z\n北京显示可转换为 UTC+08:00，原时标仍使用 UTC 语义。\n24 位分数最小步长：2^-24 s ≈ 59.6046 ns。')+p('约 60 ns 是表示分辨率，不是 IED 对 UTC 的实际误差，也不是采样周期。增加显示小数位不会提高时源准确度。')+table(['TimeQuality 分量','类型 / 存在','值域','功能'],[('LeapSecondKnown','BOOLEAN / M','false / true','基线 true 表示考虑发生的闰秒；GPS/UTC 转换按时源与映射核对'),('ClockFailure','BOOLEAN / M','false / true','true 表示时源不可靠，原文要求忽略该 TimeStamp'),('ClockNotSynchronized','BOOLEAN / O','false / true','true 表示未同步外部 UTC；原表此项为可选'),('TimeAccuracy','CODED ENUM / M','准确度代码 n','2⁻ⁿ 秒准确度间隔；不只是显示位数')])+table(['原表 9 的 n','2⁻ⁿ 近似间隔','性能级要求'],[('31','未规定','未规定'),('7','7.8 ms','T0：10 ms'),('10','0.98 ms','T1：1 ms'),('14','61 μs','T2：100 μs'),('16','15 μs','T3：25 μs'),('18','3.8 μs','T4：4 μs'),('20','0.95 μs','T5：1 μs')])+p('表中完整列出原表 9 七项，不宣称是后续全部映射代码集合。SCD DA@bType="Timestamp" 定义属性类型，DAI/Val 若有值只表示文件设置，当前时钟品质还需运行数据。')),
sec('entry','7. EntryID 与 EntryTime',table(['字段 / 类型','用途','样式与边界','SCD 关系'],[('EntryID / 字节串','BRCB 恢复、LOG 增量查询','教学 01 A2 00 10；保存原始字节，不推断为时间或序号；长度/语义由 SCSM 定义','OptFields@entryID 为字段选项，不保存每个条目 ID'),('EntryTime / SCSM 日期时间类型','报告/日志条目进入缓冲或存储的时间','人可读 2026-10-03T00:00:00Z 只是教学显示，不指定线上语法','TimeOfEntry/TimeOfLog 不等于控制块 XML 静态属性'),('DATA.t / TimeStamp','按 CDC 定义的数据时刻','事件时间和条目时间可能不同','DOType/DA@name=t、bType=Timestamp')])+p('事件可有相同时间值，时钟也可能失步。恢复时不能用自己构造的时间代替服务器 EntryID；循环日志还须核对最旧/最新条目、标识和时间范围。')),
sec('triggers','8. TriggerConditions、TrgOp 与 intgPd',table(['条件','类型 / 值域','含义 / 使用','SCD 表现'],[('data-change / dchg','BOOLEAN','值按 CDC 规则变化；测量死区可能抑制微小变化','DA@dchg + TrgOps@dchg'),('quality-change / qchg','BOOLEAN','品质改变；值相同也可能触发','DA@qchg + TrgOps@qchg'),('data-update / dupd','BOOLEAN','数据刷新，值不必变化','DA@dupd + TrgOps@dupd'),('integrity','BOOLEAN','控制块周期启动完整数据集报告/记录','TrgOps@period + intgPd'),('general-interrogation / GI','BOOLEAN','客户启动当前数据集总召唤；用于报告','TrgOps@gi 是选项，运行 GI 为请求；日志不支持 GI')])+p('TrgOp 是 DA 的事件特征，TrgOps 是控制块采用的触发。报告还要求对象属于数据集、控制块运行条件成立且报告使能。GI 和 integrity 不依赖单个 DA 的 dchg 特征。')+table(['属性','类型 / 域','功能','参考 SCD'],[('IntgPd / intgPd','INT32U；0～4294967295 ms','0 不产生周期完整性报告；大于 0 还需采用 integrity','brcbRelayEna：intgPd=0、period=false'),('GI','BOOLEAN 命令','写 true 启动，总召唤完成后自动复位','TrgOps 缺省 gi 不等于不支持；实际值按版本默认核对'),('ReasonCode','TriggerConditions','条目被包含的原因','OptFields.reasonCode 选择是否携带；不记录具体事件')])+p('bufTime=100 是事件聚合时间，不是每 100 ms 必发。intgPd=0 不会阻止 dchg/qchg 报告。'+link('scd-acsi-evidence','查看实际配置','report-evidence')))],
'5.5（表 2～10，PDF 页 12～17），10.2.2.4（表 17），第 19 章（表 42，PDF 页 111～114）。',[('acsi-server-associations','服务器与关联'),('acsi-runtime-models','运行模型')])
page('acsi-server-associations','服务器、应用关联与访问视窗','通信协议',[
sec('server','1. SERVER 的定义、语法和属性',p('SERVER 描述设备外部可见行为。所有 ACSI 模型属于服务器，但同一物理 IED 可有多个接入点、服务器模型或不同映射角色。服务器既能与客户通信，也能向对等订户发布信息。地址抽象 ServiceAccessPoint 的类型由 SCSM 定义，不直接等于一个 IP 地址。')+pre('SERVER {\n  ServiceAccessPoint [1..n] : SCSM-specific\n  LogicalDevice      [1..n] : LOGICAL-DEVICE\n  File               [0..n] : FILE\n  TPAppAssociation   [0..n] : TWO-PARTY-APPLICATION-ASSOCIATION\n  MCAppAssociation   [0..n] : MULTICAST-APPLICATION-ASSOCIATION\n  service GetServerDirectory\n}')+table(['属性名','类型 / 个数','功能 / 条件','SCD 位置与关键字'],[('ServiceAccessPoint','SCSM 特定；1..n','系统范围内寻址服务器；地址类型和内容由映射确定','IED/AccessPoint@name；Communication/SubNetwork/ConnectedAP@iedName/@apName/Address。地址 P 字段按网络/映射核对'),('LogicalDevice','LOGICAL-DEVICE；1..n','服务器包含的 LD 集合','AccessPoint/Server/LDevice@inst，版本适用时核对 ldName'),('File','FILE；0..n','服务器提供的文件对象','IED/Services/FileHandling 是能力线索；无完整 FILE 目录 XML'),('TPAppAssociation','TPAA；0..n','运行时建立的客户/服务器关联','Services/DynAssociation、Server/Authentication 仅提供线索；没有每条运行关联的 XML 实例'),('MCAppAssociation','MCAA；0..n','单向发布到订户的上下文','LN0 发布控制块 + Communication 的 GSE/SMV；没有 MCAA 标签')])+p('参考文件：IED C_G1101X → AccessPoint S1 → Server timeout="30" → LDevice LD0、MEAS 等。timeout 是 SCL Server 配置属性，不是原表 11 SERVER 的第六个抽象属性。Authentication 是 Server 子元素，地址配置位于独立的 Communication 树。网络、设备和系统管理不由本部分完整规定。')),
sec('directory','2. Directory、GetDefinition 和 GetValues 区别',table(['服务族','回答的问题','请求 / 返回','SCD 静态对照'],[('GetServerDirectory','有哪些 LD 或文件？','ObjectClass → Reference 列表','Server/LDevice；文件目录需设备查询'),('GetLogicalDeviceDirectory','这个 LD 有哪些 LN？','LDReference → LNReference 列表','LDevice/LN0、LN'),('GetLogicalNodeDirectory','这个 LN 有哪些指定类对象？','LNReference + ACSIClass → 实例名列表','LN 下的 DATA、DataSet、RCB 等'),('GetDataDirectory','这个 DATA 有哪些属性？','DataReference → DataAttributeName 列表','DOType/DA 及嵌套类型'),('GetDataDefinition','属性结构、类型与 FC 是什么？','DataReference → 完整嵌套定义','LNodeType/DO → DOType → DAType/BDA'),('GetDataValues','现在的值是什么？','FCD/FCDA → 属性值','SCD 定义与初值不能证明当前过程值')])+figure('discover','自描述服务逐级发现',[(40,20,810,65,'GetServerDirectory','LD 或 FILE 名列表'),(40,120,810,65,'GetLogicalDeviceDirectory','指定 LD 内可见的 LN 引用'),(40,220,810,65,'GetLogicalNodeDirectory','选择 DATA、DataSet、RCB 等类'),(40,320,390,70,'GetDataDirectory','属性名及层级'),(470,320,380,70,'GetDataDefinition','属性结构、类型、FC')],[(445,85,445,120),(445,185,445,220),(220,285,220,320),(660,285,660,320)],'发现是逐级查询可见模型；定义与当前值是不同服务结果。')+p('SCD 与在线目录都可帮助自描述，但二者证据不同：文件可能未更新，目录可能按客户视窗过滤。发现少了对象时，先核对版次、配置、视窗与查询类别，不直接判定设备模型不完整。')),
sec('get-server-directory','3. GetServerDirectory 请求和响应全表',p('该服务检索寻址服务器向请求客户开放的 LD 或 FILE 名列表。服务表中不另列访问点，不表示无需知道访问目标；关联/映射上下文已经确定服务器。')+table(['阶段 / 参数','类型 / 域','功能与条件','例子 / SCD 对照'],[('Request.ObjectClass','LOGICAL-DEVICE 或 FILE','选择目录对象类；不是让客户提交某个 LN 名','选择 LOGICAL-DEVICE；静态对照 Server/LDevice'),('Response+.Reference[0..n]','LD ObjectReference 或 FileName；文件名 VISIBLE STRING255','服务成功，返回可见对象引用/文件名','零项可以是成功空目录；不等于服务失败'),('Response−.ServiceError','ServiceError','请求失败，返回原因','class-not-supported、access-violation 等依实际失败情况')])+sequence('getdir','GetServerDirectory 交互',[('>','Request {ObjectClass=LOGICAL-DEVICE}'),('<','Response+ {Reference=[可见 LDRef, …]}'),('>','Request {ObjectClass=FILE}'),('<','Response+ 文件名列表 或 Response− ServiceError')],'后两行展示另一项独立请求。每次请求只返回成功或失败中的一种结果。')+pre('原创 ACSI 教学交互（不是 MMS 编码报文）：\n已建立 TPAA，目标为 C_G1101X / S1 的 Server\nRequest:   GetServerDirectory { ObjectClass: LOGICAL-DEVICE }\nResponse+: { Reference: ["C_G1101XLD0", "C_G1101XMEAS", ...] }\n另一请求可能返回：Response− { ServiceError: "access-violation" }')+p('例中的 LD 名按源 SCD 与通常 IED 名+inst 规则构造；它不是实际抓取的设备响应，省略号也不是字面返回内容。GetServerDirectory 返回目录，不建立关联、不读过程值、不获取完整类型定义。实际 MMS 映射需查 '+link('service-mapping','服务映射')+'。')),
sec('association','4. 应用关联 AA：组成与使用',p('应用关联把信息交换双方及其上下文联系起来。本章模型包括关联类型和访问控制：TPAA 为双向面向连接的信息交换，MCAA 为单向发布上下文。可靠连接可以报告未及时交付的原因并实施端到端流控制；这不意味着客户端发出的电气动作一定成功。')+table(['特征','TPAA','MCAA'],[('关系','客户与服务器建立关联','发布者与一个或多个订户'),('方向','双向','单向'),('服务形态','确认请求响应与无确认通知均可','单向无确认发布'),('典型应用','目录、读写、报告管理、控制、文件','GOOSE、GSSE、多播 SV'),('建立/结束','Associate；Release 或 Abort','按发布配置和每次报文上下文解释，不逐订户握手'),('关键边界','Report 本身是无确认服务，底层可有可靠传输','无逐订户确认，不据此断言业务方必已使用数据')])+p('服务确认与底层传输确认属于不同层次。运行关联不是 DataSet，也不是服务器 IP 地址本身。')),
sec('access-view','5. 访问控制与服务访问视窗',p('虚拟访问视窗 Virtual Access View 是服务器对某个客户开放的对象、属性和服务集合。它既限制“看见什么”，也限制“可对它做什么”。一个对象在设备中存在，不保证每个客户能发现或写入它；隐藏必选属性不会取消设备实现该属性的要求。客户端也可实施额外限制，但服务器仍负责其访问控制。')+figure('view','两个客户的虚拟访问视窗',[(30,20,840,70,'同一 SERVER 内实际模型','XCBR1.Pos、XCBR1.OpCnt、RCB、定值等'),(30,150,390,90,'客户 A 的视窗','示例：读 OpCnt；禁止操作 Pos'),(480,150,390,90,'客户 B 的视窗','示例：读 Pos/q/t；条件允许时控制'),(30,320,390,75,'A 的目录和服务结果','仅返回可见对象；越权请求被拒绝'),(480,320,390,75,'B 的目录和服务结果','能发现更多对象；控制仍受状态限制')],[(220,90,220,150),(675,90,675,150),(220,240,220,320),(675,240,675,320)],'原创视窗示意：共同实际模型，按身份和策略开放不同可见性与服务权限。视窗不是两个复制设备。')+table(['约束对象','例子','SCD 可见程度'],[('实例可见性','A 看不到某 DATA','SCD 可列实例，但不保证 A 的运行目录相同'),('属性访问','读允许，写拒绝','FC 和类型帮助判断用途；不是完整权限策略'),('服务能力','允许读，不允许 Operate','Services 是能力声明，不等于某客户授权'),('运行状态','对象被占用或当前模式不允许操作','需运行关联、模式及状态证据'),('认证','AuthenticationParameter 标识访问上下文','Server/Authentication 为配置线索；无完整用户权限矩阵')])+p('原文将认证参数结构/内容及安全要求的实现交给 SCSM。空 Authentication 元素不能证明已启用密码、证书认证或加密，也不能反向证明没有任何访问控制。')),
sec('tpaa','6. TPAA 语法、属性与服务',pre('TWO-PARTY-APPLICATION-ASSOCIATION {\n  AssociationId          : SCSM-specific\n  AuthenticationParameter: SCSM-specific\n  services: Associate, Abort, Release\n}')+table(['属性','类型 / 值域','含义与功能','使用条件 / SCD'],[('AssociationId','SCSM 特定；本部分不定义整数宽度或字符串长度','区分某条应用关联；可在线交换或只在本地使用','后续服务在相应上下文使用；不是 IED 名或 MAC'),('AuthenticationParameter','SCSM 特定；结构/合法值由映射定义','标识所需访问许可信息，不匹配时拒绝','建立关联时传递；SCD Authentication 不保存本次参数')])+table(['服务','阶段和参数','功能 / 使用时机','失败 / 结束语义'],[('Associate','Request：ServerAccessPointReference、AuthenticationParameter；Response+：AssociationId、Result','对特定服务器建立 TPAA','失败返回 ServiceError；不匹配认证参数拒绝'),('Release','Request：AssociationId；Response+：AssociationId、Result','正常结束；已发服务在结束前完成，不再发新请求','失败返回 ServiceError；不是立即丢弃所有请求'),('Abort','Request / Indication：AssociationId、Reason','突然中止；可由关联双方或下层触发','丢弃未完成请求，不再处理；不是正常成功响应式释放')])+p('Associate 的源表将否定字段写为 ServerError，紧随解释使用 ServiceError；本文按该处服务错误语义解释并保留写法差异。Result 表示关联管理操作结果，不是设备控制执行结果。')),
sec('flows','7. 正常操作与异常中止流程',sequence('normal-aa','TPAA 正常操作',[('>','Associate：服务器入口 + 认证参数'),('<','Response+：关联标识 + 结果'),('>','GetDataValues 等确认服务请求'),('<','相应 Response+ 或 Response−'),('<','Report 等无确认通知'),('>','Release：关联标识'),('<','Response+：正常结束结果')],'TPAA 支持双向确认服务，也支持服务器主动的无确认通知；Report 没有 ACSI Report 确认响应。')+sequence('abort-aa','TPAA 异常中止',[('>','已有关联，某服务请求正在处理'),('<','Abort Indication：关联标识 + 原因'),('>','后续需要访问时重新 Associate')],'示例为服务器或下层中止；客户也可主动 Abort。中止不代表之前请求已完成。')+p('关联中止后非永久数据集自动删除；URCB/USVCB 的关联保留按模型释放。BRCB 事件缓存和取代状态不能简单解释成“断线全部清零”；恢复需按各模型、设备能力及有效条目范围核对。')),
sec('mcaa','8. MCAA 功能、参数与发布订阅',p('MCAA 提供一个发布者向一个或多个订户的单向交换，携带足够上下文让订户解释数据。第 7.5 节类表唯一列出的属性是 AuthenticationParameter，类型和值域由 SCSM 确定；本部分不规定通用 AssociationId。')+table(['项目','功能 / 参数','表现与边界'],[('AuthenticationParameter','服务采用处规定的认证/访问上下文','不匹配时订户拒绝；是否/如何编码由实际映射决定'),('数据服务','SendGOOSEMessage、SendGSSEMessage、SendMSVMessage','无逐订户确认；服务采用和 TP/MC 标记见附录 A'),('发布配置','数据集、控制块、消息标识和修订','SCD GSEControl / SampledValueControl'),('网络寻址','映射定义的发送与目的地址','ConnectedAP/GSE 或 SMV/Address；APPID、MAC 不是 AA 身份的全部'),('接收配置','成员引用与订阅关系','Inputs/ExtRef 和工程通信配置；不能证明当前在线接收')])+figure('multicast','一个发布者与多个订户',[(30,140,340,80,'发布者 / Publisher','控制块 + 数据集'),(510,20,340,70,'订户 A','按配置解释上下文和成员'),(510,140,340,70,'订户 B','接收与接受策略独立'),(510,260,340,70,'订户 C','无逐订户响应箭头')],[(370,170,510,55),(370,180,510,175),(370,190,510,295)],'MCAA 单向发布示意。这里的箭头不表示各订户实际已收到或执行业务。'))],
'第 6 章（表 11，PDF 页 17～19），第 7 章（表 12、13，PDF 页 19～24），附录 A.4。',[('acsi-runtime-models','关联之后的数据与服务'),('scd-acsi-evidence','SCD 配置位置')])
FCROWS=[('ST','Status information','状态','读、报告、日志；不能直接写过程状态'),('MX','Measured value','测量','读、报告、日志；取代经 SV 实现'),('CO','Control','控制','按控制状态机操作；非普通任意写入'),('SP','Setpoint','设点','按适用模型读/控制，值即时生效'),('SV','Substitution','取代','读/写取代值、品质、标识和使能'),('CF','Configuration','配置','可读；写入仍受属性和实现条件限制'),('DC','Description','描述','可读/写适用描述属性'),('SG','Setting group','激活定值组','读当前激活视图；不能直接写'),('SE','Setting group editable','编辑定值组','选择编辑组后读写编辑缓冲'),('EX','Extended definition','扩展定义','扩展语义和命名空间；基线不可写'),('BR','Buffered report','缓存报告控制','BRCB 属性分组'),('RP','Unbuffered report','非缓存报告控制','URCB 属性分组'),('LG','Log control','日志控制','LCB 属性分组'),('GO','GOOSE control','GOOSE 控制','GoCB 属性分组'),('GS','GSSE control','GSSE 控制','GsCB 属性分组'),('MS','Multicast sampled value control','多播采样控制','MSVCB 属性分组'),('US','Unicast sampled value control','单播采样控制','USVCB 属性分组'),('XX','Wildcard in services','服务通配','仅表示任意适用 FC，不给属性定义 fc=XX')]
ADDCAUSE=[('Blocked-by-switching-hierarchy','开关控制层级限制'),('Select-failed','选择失败'),('Invalid-position','当前开关位置无效'),('Position-reached','对象已处于目标位置'),('Parameter-change-in-execution','执行中参数改变'),('Step-limit','分接位置到达上/下限'),('Blocked-by-Mode','LN 或设备模式不允许操作'),('Blocked-by-process','外部过程条件阻止操作'),('Blocked-by-interlocking','联锁条件不满足'),('Blocked-by-synchrocheck','同期检查不满足或超时'),('Command-already-in-execution','已有命令执行中'),('Blocked-by-health','内部健康状态限制'),('1-of-n-control','同一控制域已有其他动作'),('Abortion-by-cancel','因取消服务终止'),('Time-limit-over','控制超时'),('Abortion-by-trip','因保护跳闸终止')]
page('acsi-runtime-models','第 8～17 章：数据、交换与控制模型','数据模型',[
sec('data','1. LD、LN、DATA 与属性组成',table(['类 / 属性','类型或基数','功能 / 存在条件','SCD 位置'],[('LDName / LDRef','ObjectName / ObjectReference','LD 实例名与唯一引用；LD 位于引用顶层，所以二者值相同','LDevice@inst 与 IED/适用命名规则'),('LogicalNode','原基线表 14：3..n','一个 LLN0、一个 LPHD，至少一个其他 LN；这是所给早期版定义','LDevice/LN0、LN；后续版与工程实例按实际规则核对'),('LNName / LNRef','ObjectName / ObjectReference','LD 内唯一名 / LDName/LNName 路径','prefix + lnClass + inst；lnType 指向 LNodeType'),('Data[1..n]','DATA','LN 至少包含一个 DATA','LNodeType/DO，DOI 仅是实例设置而非完整 DO 清单'),('DataSet / BRCB / URCB / LCB','各类 0..n','LN 的数据集与交换控制对象','DataSet、ReportControl、LogControl'),('SGCB / LOG','原表 15：各 0..1','定值组和日志模型；实际采用位置与映射再核对','SettingControl 通常在 LN0；Log 配置存储实例'),('GoCB / GsCB / MSVCB / USVCB','各 0..n','相应事件/样本发布控制对象','GSEControl、SampledValueControl，按 SCL 放置规则'),('DataName / DataRef','ObjectName / ObjectReference','DATA 的名与路径','DO@name、SDO@name 与实例层级'),('Presence','BOOLEAN','基线 true=必选，false=可选；不是业务 true/false','模板/实例存在性与标准 M/O/条件规则共同核对'),('DataAttributeType / FC / TrgOp','DAType / FC / TriggerConditions','属性类型、访问用途与事件特征','DOType/DA 的 bType/type/fc/dchg/qchg/dupd'),('CompositeCDC / SimpleCDC','递归 DATA 特例','可组合子数据或属性；所有组成不能同时为空','DOType/SDO、DOType/DA；WYE 可含 CMV 子数据')])+p('DATA 是抽象框架，CDC 是结构和行为特例，7-4 的 Pos 等数据名再赋予具体功能语义。XCBR1.Pos、CSWI1.Pos 属于不同 LN，不能只看到 Pos 就认定是同一对象。结构 DAType 和 CDC 都能组合，但前者组织属性分量，后者组织数据语义。')+table(['服务','请求要点','成功结果','使用'],[('GetLogicalDeviceDirectory','LDReference','可见 LNReference 列表','发现 LD 功能节点'),('GetLogicalNodeDirectory','LNReference + ACSIClass','指定类的实例名；空列表可以成功','发现 DATA/DS/RCB 等'),('GetAllDataValues','LNReference + 可选 FC','属性引用与相应值','读取 LN 的适用属性快照'),('GetDataValues','FCD 或 FCDA Reference','对应 DataAttributeValue 列表','读取对象或单属性'),('SetDataValues','Reference + 对应值','接受并传入应用；实际应用动作按模型','写允许属性；不替代 Operate'),('GetDataDirectory','DataReference','属性名列表','发现组成'),('GetDataDefinition','DataReference','所有嵌套属性类型和 FC 定义','确认结构与解释方法')])+p('以上确认服务失败返回 ServiceError；访问仍受视窗、类型和状态限制。读目录不是读值，写值成功也不能代替机械动作完成证明。')),
sec('fc','2. FC 全部基线值及 FCD / FCDA',table(['FC','英文用途','中文','读法与边界'],FCROWS)+p('FC 筛选属性用途，不改变 DATA 对象身份。原表 18 的 Da/CB 列区分 DATA 属性与控制块属性采用场合，不能看见某 FC 就假定任意服务可写。FCD=(DataRef,FC)，FCDA=(DataAttributeReference,FC)，二者的具体记法由 SCSM 定义。完整名称与字符规则见 '+link('acsi-common-types','对象引用','references')+'。')),
sec('dataset','3. 数据集：概念、类别与生命周期',p('DATA-SET 是至少一个 FCD/FCDA 的有序引用集合。双方已知成员与顺序时，不必每次重复发送全部成员名字。一个 DATA/DA 可被多个数据集引用，成员不是新建业务数据副本；数据集可以跨 LN、按适用规则引用 LD 中的成员。DataSet 名本身不能证明用于何种业务，必须查控制块或读写引用。')+table(['属性','类型 / 域','功能','SCD'],[('DSName','ObjectName','LN 或 TPAA 内唯一名','DataSet@name'),('DSRef','ObjectReference 或关联专用引用','永久路径 / @DataSetName','由 IED、LD、LN、name 重建'),('DSMemberRef[1..n]','FCD/FCDA 引用','保持成员顺序，所引用对象必须存在','按 XML 顺序的 FCDA；doName、daName、fc 等')])+table(['类别','创建 / 可见','关联结束','删除 / 使用约束'],[('预配置数据集','SCL/本地配置；按视窗向客户开放','继续存在','基线不可由 DeleteDataSet 删除'),('动态永久数据集','CreateDataSet，LD/LN 路径；按视窗可对其他客户可见','保留；“永久”不自动证明掉电非易失','可删除，但被控制类引用时受到约束'),('动态非永久数据集','CreateDataSet，@名；仅创建它的客户关联可见','自动删除','基线仅供 URCB、USVCB 引用；不用于 GOOSE/BRCB')])+table(['服务','请求 / 成功结果','使用时机'],[('GetDataSetValues','DSRef → 按成员顺序的值','批量快照读取'),('SetDataSetValues','DSRef + 对应值 → 成功/成员结果按映射','设置允许写的成员；不是批量开关遥控'),('CreateDataSet','DSRef + DSMemberRef[1..n] → 创建结果','设备支持动态创建且成员可访问'),('DeleteDataSet','DSRef → 删除结果','仅可删除且未受引用/使用限制的实例'),('GetDataSetDirectory','DSRef → DSMemberRef 有序表','确认成员、引用与顺序')])+p('SCL 的 FCDA 元素既能表达 FCD（有 doName、fc，省略 daName），也能表达单属性/分量（给出 daName）。FCD 可能展开多个值，因此 XML FCDA 数量不能直接等同于报文的标量数。数据集重排会改变接收解释，应协调控制块修订和订阅配置。')+figure('ds-life','数据集生命周期',[(30,20,840,70,'预配置 DataSet','随工程配置提供；基线不能由删除服务删除'),(30,150,390,80,'CreateDataSet：永久路径','关联结束后保留；引用期间受删除约束'),(480,150,390,80,'CreateDataSet：@关联专用名','只对创建关联可见；用于 URCB/USVCB'),(30,310,390,70,'关联 Release / Abort','动态永久实例继续存在'),(480,310,390,70,'关联 Release / Abort','非永久实例自动删除')],[(220,230,220,310),(675,230,675,310)],'预配置、动态永久和动态非永久是三类不同生命周期，不能用文件内有 DataSet 推断运行时动态创建支持。')),
sec('substitution','4. 取代：改变数据来源，不直接操控一次设备',p('取代用指定值与品质替代 ST/MX 数据对外呈现的过程值。常见场景是受控地处理异常或失效数据源。该机制不等于写 stVal、不等于测试模式，也不保证改变外部设备真实状态。原文明确取代属于正常操作模型，测试另由模式或服务 Test 参数表达。')+table(['属性','类型 / FC','作用','使用顺序'],[('subVal / subMag / subCMag','随 CDC 的值/结构类型；SV','待取代的状态、幅值或复数量','先准备替代值'),('subQ','Quality；SV','替代品质','与值共同准备，按模型反映来源/有效性'),('subID','CDC 规定字符串；SV','标识启动取代者','按应用规程设置'),('subEna','BOOLEAN；SV','true 采用替代值，false 恢复过程来源','准备值/品质/标识之后再使能')])+pre('原创教学顺序（只解释服务，不提供操作功能）：\n1. SetDataValues 写 subVal/subQ/subID（FC=SV）\n2. SetDataValues 写 subEna=true（FC=SV）\n3. GetDataValues 或报告读取 ST/MX 视图及品质\n4. 退出时将 subEna=false，并核对恢复后的来源/品质')+p('本模型复用数据读写服务，没有独立“Substitute”报文。关联断开不能自动推断取代立即退出；保持/退出需核对当地行为。参考 SCD 类型库包含 subEna BOOLEAN、subVal BOOLEAN、subQ Quality、subID VisString64，FC 均为 SV；类型存在不证明当前已取代。')),
sec('settings','5. 定值组：编辑、确认与激活分开',p('SG 是一组共同切换的参数值，SGCB 管理多个组及激活/编辑缓冲。同一 LD 的多个 LN 可以共用一个定值组控制过程。当前激活组以 FC=SG 读；选定编辑组后以 FC=SE 访问编辑缓冲，确认后才把缓冲提交到该组，激活又是另一项服务。')+table(['SGCB 属性','基线类型 / 域','含义','SCD 表现'],[('SGCBName / SGCBRef','ObjectName / ObjectReference','标准化 SGCB 名及 LD/LLN0.SGCB 引用','SettingControl 不用 name 重建任意 SGCB 名'),('NumOfSG','INT8U；可用组数≥1','总组数，不由普通服务任意写','SettingControl@numOfSGs'),('ActSG','INT8U；1..NumOfSG','当前激活组','SettingControl@actSG 为配置值'),('EditSG','INT8U；0 或 1..NumOfSG','0 没有选择编辑组，此时编辑读写拒绝','运行时状态，不能从 actSG 代推'),('CnfEdit','BOOLEAN','确认编辑过程','运行命令，不是静态已确认标志'),('LActTm','原表 22：TimeStamp','最近激活时间','无同名静态 SettingControl 属性')])+table(['服务','请求 / 成功结果要点','条件 / 意义'],[('SelectActiveSG','SGCBReference + SettingGroupNumber','选择激活组；不等于选择编辑'),('SelectEditSG','SGCBReference + SettingGroupNumber','选择编辑缓冲；须符合访问与占用条件'),('SetSGValues','SE 的 FCD/FCDA + 值','写编辑组；原文正文另出现 SetEditSGValues 写法'),('ConfirmEditSGValues','SGCBReference → Result','提交编辑缓冲；原文正文也用单数 ConfirmEditSGValue'),('GetSGValues','SG/SE 的引用 → 对应值','区分激活与编辑视图'),('GetSGCBValues','SGCBReference + FC → 组数/激活组/编辑组/激活时间','读控制状态')])+figure('sg-flow','定值组缓冲与激活',[(30,20,840,70,'定值组存储：SG1 … SGn','一组可覆盖 LD 内多个 LN 的参数'),(30,160,390,80,'SelectActiveSG → 激活缓冲','FC=SG 读；运行功能使用该组'),(480,160,390,80,'SelectEditSG → 编辑缓冲','FC=SE 读写；尚未提交'),(480,330,390,70,'ConfirmEditSGValues','提交所选组；激活仍是独立操作')],[(220,90,220,160),(675,90,675,160),(675,240,675,330)],'编辑成功、确认成功和激活成功对应不同状态，不应合并。')+p('真实配置 PCK1101X/S1/PROT/LLN0：numOfSGs=15、actSG=1。它说明文件配置的组数与激活组初值，不能证明当前运行仍在第 1 组，也不能说明第 15 组的具体整定值。')),
sec('report','6. 报告：BRCB、URCB 与恢复',p('报告由服务器向客户主动发送数据集变化或完整快照。Report 本身是无确认 ACSI 服务，传输层可靠性不能替代客户端入库证明。一个报告实例在同一时刻受一个客户使用/保留；多客户接收通常需要可用实例或映射规定的客户视图。')+table(['属性','类型 / 域','功能 / 条件','SCD'],[('BRCBName/BRCBRef、URCBName/URCBRef','ObjectName/ObjectReference','实例名与定位','ReportControl@name，运行索引实例名按映射'),('RptID','VISIBLE STRING65','报告标识','rptID'),('RptEna','BOOLEAN','运行报告使能；使能状态限制大部分配置修改','无同名配置属性；buffered 仅选类'),('Resv（URCB）','BOOLEAN','客户保留；使能也有隐含保留语义','运行时，不从 RptEnabled.max 代推'),('DatSet','ObjectReference','被监视数据集','datSet 是同 LN 数据集名称'),('ConfRev','INT32U；基线 0 保留','跟踪数据集成员/顺序等配置修订','confRev'),('OptFlds','PACKED-LIST','字段选项；BRCB 有溢出、EntryID 等特有内容','OptFields'),('BufTm','INT32U，ms','事件聚合时间，非历史缓存容量','bufTime'),('SqNum','基线 BRCB INT16U；URCB 表 25 INT8U','报告序号；实际编码按映射核对','运行值；不把其他模型 SqNum 混用'),('TrgOp/TrgOps','TriggerConditions','变化/刷新/完整性/GI 条件','TrgOps'),('IntgPd','INT32U，ms；0 禁用周期','完整性周期','intgPd'),('GI','BOOLEAN 命令','启动当前快照，完成自动复位','gi 是配置选项，不是运行请求'),('PurgeBuf（BRCB）','BOOLEAN 命令','舍弃缓存事件，完成复位','无同名静态 XML 属性'),('EntryID / TimeOfEntry（BRCB）','EntryID / EntryTime','恢复位置与入缓冲时间','OptFields 选择字段，但不存运行条目')])+table(['比较','BRCB','URCB'],[('断线/传输受限','在容量和模型条件内缓存事件','不提供 BRCB 式断线事件缓存'),('恢复','可按最后 EntryID 重同步；核对溢出、修订及保留范围','重建关联、重新配置/使能；GI 可得当前快照'),('GI','当前数据集快照，不替代丢失历史','同样不能补回断线期间所有变化'),('使能期间写配置','通常先停止使能，按模型允许项写','同样受运行状态及保留限制'),('静态类选择','buffered=true','buffered=false')])+p('报告格式包含 RptID、OptFlds，按选项包含 SqNum、分段相关 SubSqNum/MoreSegmentsFollow、DatSet、BufOvfl、ConfRev、TimeOfEntry、EntryID，以及各条目的 DataRef、Value 和 ReasonCode。每个字段的采用条件按表 24 与映射核对；报告只含被纳入的成员时，用映射中的成员位置/包含信息解释，不可按全数据集重新错位排列。')+sequence('report-flow','报告配置和异步发送',[('>','GetBRCBValues：核对数据集、修订、选项和运行状态'),('>','按模型条件配置 RCB / 设置恢复 EntryID'),('>','SetBRCBValues：RptEna=true'),('<','Response+：使能请求成功'),('<','Report：事件或完整快照，无 ACSI 确认'),('>','需要当前快照时请求 GI=true')],'运行教学流程，配置写入仍需设备能力和合法状态；不会自动证明历史事件完整。')+p('Get/SetBRCBValues、Get/SetURCBValues 管理控制块；Report 传值。断线重连后按保存的 EntryID 续送之前要确认条目仍存在、缓存未溢出且配置一致。清缓存、改 DatSet 等可能影响恢复，不能把一次 GI 当成历史补送。参考文件 822 个 buffered=true、157 个 false，是 XML 声明计数，不是当前连接数。')),
sec('log','7. LCB、LOG、日志条目与查询',p('LCB 决定如何记录，LOG 是存储。多个 LCB 可写入一个 LOG；记录与客户查询异步，关联断开不等于停止当地日志。循环存储可能覆盖旧条目，不能默认永久保留。')+table(['对象 / 字段','类型 / 作用','使用时机 / SCD'],[('LCBName / LCBRef','ObjectName / ObjectReference','LogControl@name 定位控制对象'),('LCBEna（原文）/ LogEna（其他写法）','BOOLEAN；日志使能','XML logEna 仅文件配置'),('DatSet / LogRef','ObjectReference；来源集 / 目标日志','datSet、logName，目标 LD/LN 信息按适用 XML 配置'),('OptFlds / TrgOp / IntgPd','原因选项、四项触发和周期','reasonCode、TrgOps、intgPd；日志不支持 GI'),('LogName / LogRef','存储实例名及引用','Log；不等于 LogControl@name'),('OldEntr / NewEntr','EntryID；最旧/最新条目','GetLogStatusValues 用于判断查询范围'),('OldEntrTm / NewEntrTm','EntryTime；最旧/最新时间','不是静态 LogControl 属性'),('EntryID / TimeOfLog / EntryData','条目标识、入库时间、数据引用/值/原因','查询返回的运行记录')])+table(['服务','参数与结果','用途'],[('GetLCBValues / SetLCBValues','LCBReference + FC=LG；属性列表','读/设置记录规则'),('GetLogStatusValues','LogReference → 最旧/最新 ID 和时间','确定仍保留的历史范围'),('QueryLogByTime','LogReference + RangeStartTime/RangeStopTime → ListOfLogEntries','按时间范围，基线起止边界包括等值'),('QueryLogAfter','LogReference + RangeStartTime + Entry → ListOfLogEntries','从指定条目标识/时间之后增量读取')])+p('不能将 QueryLogAfter 简化为“数值 ID 加一”。应使用服务器返回的原条目标识和时间，按映射识别范围与分页。参考文件有 98 个 LogControl，但没有 Log 元素；配置摘录中的 logName=LD0 不能证明运行日志路径或存储状态，需目录与设备资料核实。完整 XML 字段详见 '+link('control-blocks-reference','日志控制块属性参考')+'。')),
sec('gse','8. 通用事件 GSE：GOOSE 和 GSSE',p('GSE 是通用事件模型族，GOOSE 和 GSSE 是该早期版本的两种模型，不能互换。GOOSE 发布由 DataSet 组织的有序数据；GSSE 是早期状态集合。接收方按修订、上下文、测试和有效期等解释，不是看见 MAC/APPID 就能确定实际业务。')+table(['GoCB 字段','类型 / 域','用途 / SCD'],[('GoCBName / GoCBRef','ObjectName / ObjectReference','name；抽象引用 LD/LLN0.控制块名'),('GoEna','BOOLEAN','运行发布使能，不能由存在 GSEControl 推定'),('AppID','VISIBLE STRING65','抽象应用标识；SCL appID 字符串与网络 APPID 数值区分'),('DatSet','ObjectReference','datSet 指定有序数据集'),('ConfRev','INT32U，0 保留','成员、顺序或引用等配置修订；不是报文状态号'),('NdsCom','BOOLEAN','需要进一步配置；数据集未指定/超出限制等由模型与实现判断')])+table(['服务 / 信息','功能','边界'],[('SendGOOSEMessage','经 MCAA 发布数据','无逐订户确认'),('GetGoReference','GoCBReference + MemberOffset → 成员引用及修订','原文成员从 1 编号；不能直接套某工具的 0 索引'),('GetGOOSEElementNumber','成员引用 → 数据集位置','核对成员位置，不是只返回全成员个数'),('GetGoCBValues / SetGoCBValues','读/设置控制属性，FC=GO','使能时配置修改受限制'),('GOOSE message','GoCBRef、TimeAllowedToLive、DatSet、AppID、T、StNum、SqNum、Test、ConfRev、NdsCom、GOOSEData','抽象参数与具体 8-1 字段写法/编码分开')])+p('StNum 表示状态变化，SqNum 表示发送序列。重发、计数复位与溢出的实际规则要按映射，不能只凭本早期概念表推断所有设备实现。T 与成员 t 也不一定同一含义；Test=true 的接受策略不能省略。')+table(['GsCB 字段 / 服务','基线类型 / 功能','使用说明'],[('GsCBName / GsCBRef','ObjectName / ObjectReference','定位 GSSE 控制块'),('GsEna','BOOLEAN','使能；使能期间配置受限制'),('AppID / DataLabel','VISIBLE STRING65','应用和状态标签'),('LSentData','GSSEData 状态集合','最近发送值；规模受 SCSM/设备限制'),('GSSEData.Value','CODED ENUM：0 无效/瞬变，1 假/合，2 真/开，3 无效','这是原文 GSSE 语义，不套作所有开关 stVal 的通用编码'),('SendGSSEMessage','发送状态集合','历史基线知识'),('GetGsReference / GetGSSEDataOffset','标签/引用与偏移之间对应','用于理解状态序列'),('GetGsCBValues / SetGsCBValues','FC=GS 控制属性读写','不等于 GoCB 服务')])+p('本工程 GSEControl 全部 type=GOOSE，未观察到 GSSE；这是文件观察集合，不是对整个标准适用范围的否定。')),
sec('sampled-values','9. SV：多播、单播和采样格式',table(['属性','基线类型 / 域','功能 / 配置'],[('MsvCBNam/MsvCBRef 或 UsvCBNam/UsvCBRef','ObjectName/ObjectReference','控制块定位；SampledValueControl@name'),('SvEna','BOOLEAN','运行采样传输使能'),('Resv（仅 USVCB）','BOOLEAN','关联客户保留；关联结束释放并停止传输'),('MsvID / UsvID','VISIBLE STRING65','消息标识；SCL smvID'),('DatSet / ConfRev','ObjectReference / INT32U','成员引用与修订；datSet/confRev'),('SmpRate','基线 INT16U','采样率；XML smpRate 与 smpMod 决定单位，不能一律当 Hz'),('OptFlds','refresh-time、sample-synchronised、sample-rate','SmvOpts 的配置选择，不证明当前同步')])+table(['模型 / 服务','采用方式','条件 / 结果'],[('MSVCB：SendMSVMessage','MCAA 多播','连续发布给多个订户'),('USVCB：SendUSVMessage','TPAA 单播','客户建立关联、保留和使能；关联结束停止'),('Get/SetMSVCBValues','FC=MS','读写控制属性；使能时修改受限制'),('Get/SetUSVCBValues','FC=US','单播控制属性和客户保留')])+table(['采样格式字段','基线类型 / 作用','阅读要点'],[('MsvID / UsvID、OptFlds、DatSet','标识、选项、有序成员','接收方需要正确数据集解释'),('Sample[1..n] / Value','成员样本值，类型按 CDC','不是每个样本都自带工程语义名称'),('SmpCnt','INT16U；采样计数','检查顺序；同步事件复位按映射'),('RefrTm','EntryTime；刷新时间','是否携带按选项，语义按映射'),('ConfRev','INT32U','配置修订'),('SmpSynch','基线 BOOLEAN','后续具体映射可能有不同取值，不混写'),('SmpRate','INT16U','按选项携带；单位依实际采用规范')])+p('参考 smpRate=80、nofASDU=1。在额定 50 Hz、SmpPerPeriod 且每次一个样本的教学前提下，80×50=4000 样本/秒；文件本身不能证明所有这些现场前提。SmvOpts.sampleSynchronized=true 是配置字段选择，不是同步成功证明。参考出现 dataRef，而既有 B4 模式核对使用 dataSet，这一差异保留，不静默修复原 SCD。详见 '+link('control-blocks-reference','采样控制块与 B4 字段')+'。')),
sec('control','10. 控制：普通/增强安全、直接/SBO 与时间激活',p('Control 对可控 DATA 发出动作请求。普通/增强安全是控制模型的行为分类，不等于密码强度或网络加密。SBO 防止其他客户在有效选择期间竞争；增强安全增加带值选择及最终命令终止语义。收到 Operate 成功响应还不能据此宣布一次设备已到位。')+table(['ctlModel','值域代码','流程','结果判断'],[('status-only','0','仅状态','不可控'),('direct-with-normal-security','1','Operate','结合实际反馈；无增强 CommandTermination 过程'),('sbo-with-normal-security','2','Select → Operate','选择资格、超时和反馈'),('direct-with-enhanced-security','3','Operate → CommandTermination','请求接受与最终结果分开'),('sbo-with-enhanced-security','4','SelectWithValue → Operate → CommandTermination','检查选择值/参数一致、超时及最终结果')])+table(['参数 / 属性','类型 / 域','功能 / 条件'],[('ControlObjectReference','ObjectReference','定位 Pos 等可控 DATA'),('Value / ctlVal','由可控 CDC 定义','操作值；携带的 origin/ctlNum 等按模型和映射'),('origin / ctlNum','Originator 结构 / 序号类型按 CDC','发起者及控制序列，不凭名字推断人身份'),('T','基线表 36：EntryTime','客户发送控制请求的时间；具体映射再核对'),('Test','BOOLEAN：false 常规，true 测试','路径参数；不保证物理输出自动隔离'),('Check','PACKED-LIST：synchrocheck、interlock-check','true 请求相应检查；false 不取消其他约束'),('operTim','操作时间类型按 CDC/映射','时间激活的目标时刻，不与请求时标 T 混同'),('sboTimeout / sboClass','超时 / operate-once 或 operate-many','选择保持、一次/多次行为；按 CDC 实际属性名核对'),('TimOperRsp','timer-activated / command-executed','定时器启动和命令执行是不同响应阶段'),('AddCause','ENUMERATED','控制失败或终止附加原因')])+table(['服务','使用时机','成功 / 失败重点'],[('Select','普通 SBO 选择','返回选择资格相关结果'),('SelectWithValue','增强 SBO 带值选择','预先给值、Test/Check 等；失败 AddCause'),('Cancel','取消选择或适用等待过程','按状态机结束，不保证撤回已经完成的物理动作'),('Operate','执行当前请求','请求接受不等于最终机械完成'),('CommandTermination','增强安全最终结束通知','成功/失败终止与状态报告分别解释'),('TimeActivatedOperate','预约动作时间','先 timer-activated，再适用执行阶段；到时条件仍须满足')])+sequence('control-flow','增强安全 SBO 成功路径',[('>','SelectWithValue：对象、值、Test、Check'),('<','Response+：选择成功'),('>','Operate：匹配的选择参数'),('<','Response+：操作请求接受'),('<','Report：按配置报告状态变化'),('<','CommandTermination+：控制过程结束结果')],'原创流程；失败路径可能在选择、操作或执行监视阶段出现，不能仅凭响应成功判定一次动作已完成。')+p('原文表 39 列出 16 项 AddCause 专用名称；表 40 还解释可以采用表 5 的基础服务错误。下面按这份基线列全专用原因，不追加后续版新增枚举或自行指定协议数值码。')+table(['AddCause 基线名称','含义'],ADDCAUSE)+p('参考 SCD 的 ctlModel 设置出现 status-only、direct-with-normal-security、sbo-with-enhanced-security；这些是文件中的 DAI/Val，不是当前动作许可。控制对象还要沿 lnType → DOType/DA 确认 CF 的 ctlModel、CO 属性、状态、检查与反馈。设备当前模式、健康、占用和时间条件需要运行证据。'))],
'第 8～17 章，表 14～41；全服务名与原文命名差异结合 ACSI 服务分类专题。',[('scd-acsi-evidence','真实工程对照'),('acsi-engineering-workflows','时间与工程核查')])
from collections import Counter
from copy import deepcopy
import hashlib
scdpath=ROOT/'source/南雷变2026041614.scd';r=ET.parse(scdpath).getroot();ns=r.tag.split('}')[0][1:];T=lambda s:'{'+ns+'}'+s
ET.register_namespace('',ns)
counts=Counter(x.tag.split('}')[-1] for x in r.iter())
def locate(target):
 for ied in r.findall(T('IED')):
  for ap in ied.findall(T('AccessPoint')):
   for ld in ap.findall('.//'+T('LDevice')):
    for ln in list(ld):
     cb=ln.find(T(target))
     if cb is not None:return ied,ap,ld,ln,cb
 raise ValueError(target)
def xml(x):
 y=deepcopy(x)
 for el in y.iter():el.tail=None;el.text=el.text.strip() if el.text and el.text.strip() else None
 ET.indent(y,space='  ');return ET.tostring(y,encoding='unicode')
def ctx(parts):
 i,a,l,n,c=parts;return f'IED={i.get("name")} / AccessPoint={a.get("name")} / LDevice={l.get("inst")} / LN={n.get("prefix","")+n.get("lnClass","")+n.get("inst","")}'
def extract(target):
 parts=locate(target);i,a,l,n,c=parts;b=p('准确位置：<code>'+html.escape(ctx(parts))+'</code>。')+pre(xml(c),'xml')
 if c.get('datSet'):
  ds=next(x for x in n.findall(T('DataSet')) if x.get('name')==c.get('datSet'));short=ET.Element(T('DataSet'),ds.attrib)
  for member in ds.findall(T('FCDA'))[:3]:short.append(deepcopy(member))
  b+=p(f'对应 DataSet={ds.get("name")}；下列仅展示前 3 个成员，共 {len(ds.findall(T("FCDA")))} 个 FCDA。省略成员没有重排；这是摘录，不是可投产完整数据集。')+pre(xml(short),'xml')
 return b
stats=[(key,str(counts[key]),meaning) for key,meaning in [('IED','物理装置配置项'),('AccessPoint','接入点配置项'),('Server','服务器配置项'),('LDevice','逻辑设备'),('LN0','管理逻辑节点'),('LN','其他逻辑节点'),('DataSet','预配置成员清单'),('FCDA','XML 成员引用，不等于标量值数'),('ReportControl','822 个缓存、157 个非缓存'),('LogControl','日志记录配置'),('Log','未观察到 Log 元素；不据此断定运行无日志'),('SettingControl','定值组配置'),('GSEControl','全部 type=GOOSE'),('SampledValueControl','采样发布配置'),('DAType','结构属性模板')]]
manifest={'source':'source/南雷变2026041614.scd','sha256':hashlib.sha256(scdpath.read_bytes()).hexdigest(),'rootAttributes':r.attrib,'counts':dict(counts),'examples':{x:{'position':ctx(locate(x)),'attributes':locate(x)[4].attrib} for x in ['ReportControl','LogControl','GSEControl','SampledValueControl','SettingControl']},'boundary':'XML structure and observed configuration only; no full XSD validation or device/field verification.'}
(OUT/'data/part72-evidence.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
ied=next(x for x in r.findall(T('IED')) if x.get('name')=='C_M1101X');ap=next(x for x in ied.findall(T('AccessPoint')) if x.get('name')=='S1');ld=next(x for x in ap.findall('.//'+T('LDevice')) if x.get('inst')=='MEAS');ln=next(x for x in ld.findall(T('LN')) if x.get('prefix')=='GO' and x.get('lnClass')=='GGIO' and x.get('inst')=='1');types=r.find(T('DataTypeTemplates'));typeindex={x.get('id'):x for x in types};lt=typeindex[ln.get('lnType')];do=next(x for x in lt.findall(T('DO')) if x.get('name')=='AnIn1');dt=typeindex[do.get('type')];dat=typeindex[next(x for x in dt.findall(T('DA')) if x.get('name')=='mag').get('type')]
typechain=table(['追踪点','源文件字段','解释'],[('LN','prefix=GO，lnClass=GGIO，inst=1；lnType='+ln.get('lnType'),'完整 LN 名 GOGGIO1'),('LNodeType / DO','AnIn1 → '+do.get('type'),'在 LN 类型中找到 DO 类型'),('DOType','id='+dt.get('id')+'，cdc='+dt.get('cdc'),'AnIn1 在此模板采用 MV'),('DA mag','bType=Struct，fc=MX，dchg=true，type='+dat.get('id'),'结构属性，允许值变化特征'),('BDA f',str(next(x.attrib for x in dat.findall(T('BDA')) if x.get('name')=='f')),'叶子基本类型来自实际 BDA'),('DA q / t','q: Quality，MX，qchg=true；t: Timestamp，MX','品质和时标分开追踪；不是 mag.f 自带全部信息')])
conn=next(x for x in r.iter(T('ConnectedAP')) if x.get('iedName')=='C_M1101X' and x.get('apName')=='S1');gse=next(x for x in conn.findall(T('GSE')) if x.get('cbName')=='GO_Gcb1' and x.get('ldInst')=='MEAS')
page('scd-acsi-evidence','参考 SCD：ACSI 配置位置与真实引用链','SCL 配置',[
sec('positions','1. 模型到 SCD 的位置对照',p('源文件保留中文描述、模型名和类型 ID；本文优先展示可追踪的 XML 配置关系，不按厂商名、装置名或地址猜测业务。根元素标注 version=2007、revision=B、release=4；XML 命名空间仍为 http://www.iec.ch/61850/2003/SCL，命名空间里的年份不等于该文件版次。')+table(['ACSI 内容','SCD 位置','可看到什么 / 不能看到什么'],[('SERVER / 服务访问点','IED/AccessPoint/Server；Communication/ConnectedAP','模型容器和地址配置 / 非当前连接状态'),('LD / LN / DATA','Server/LDevice/LN0、LN；DataTypeTemplates','功能模型和模板 / 非完整当前值'),('DataSet / FCD / FCDA','LN0 或 LN/DataSet/FCDA','引用与顺序 / 非传输成功证明'),('BRCB / URCB','ReportControl、TrgOps、OptFields、RptEnabled','配置和资源描述 / 非 RptEna 与本次 EntryID'),('LCB / LOG','LogControl / Log','记录规则和存储配置 / 非历史条目'),('SGCB','LN0/SettingControl；DA 的 SG/SE','组数和初始激活组 / 非编辑确认过程'),('GoCB / MSVCB','GSEControl / SampledValueControl','发布配置 / 非当前发送、接收或同步状态'),('CONTROL','DOType/DA、DOI/SDI/DAI 的 ctlModel 等','对象控制模型 / 非当前控制资格与执行结果'),('TPAA / MCAA / 权限','Authentication、Services、发布和订阅配置','能力/配置线索 / 非关联和用户授权全表'),('文件 / 时间','FileHandling、时间属性或采样选项','能力与类型线索 / 非文件目录或对时成功')])+table(['元素','数量','说明'],stats)+p('统计来自 XML 结构读取，不宣称通过完整 XSD 校验；源文件 SHA-256 和例子位置见本地 <a href="../data/part72-evidence.json">证据清单</a>。该 JSON 可直接打开查阅，不通过 fetch 加载，离线页面无服务器依赖。')),
sec('report-evidence','2. 报告配置：brcbRelayEna 与 FCD 成员',extract('ReportControl')+table(['实际字段','解读','不能推断'],[('buffered=true','选择 BRCB 类','当前报告已使能'),('datSet=dsRelayEna','引用同 LN 数据集','名称对应实际业务的全部语义'),('bufTime=100','事件聚合配置 100 ms','每 100 ms 固定发一次'),('intgPd=0；period=false','未配置周期完整性报告','不会发生变化报告或不支持 GI'),('dchg=true / qchg=true / dupd=false','采用值变化和品质变化条件','模板任意属性都能触发'),('OptFields entryID/timeStamp/dataRef 等','选用相应报告字段','SCD 保存实际条目或能保证不丢失'),('RptEnabled max=16','声明最大报告实例相关资源','当前有 16 个已连接客户')])+p('成员 FunEna1 带 ST 而不带 daName，是 FCD；应沿 LLN0 的 lnType 找到该 DO，再从 DOType 选择 fc=ST 的属性。不能把这一项机械解释为只发送一个布尔值，也不能把文件 desc 当成完整的现场动作定义。')),
sec('goose-evidence','3. GOOSE：控制块、成员和通信配置',extract('GSEControl')+p('同一引用链的通信位置：Communication/SubNetwork/ConnectedAP，iedName=C_M1101X、apName=S1；GSE 用 ldInst=MEAS 与 cbName=GO_Gcb1 对应发布控制块。')+pre(xml(gse),'xml')+typechain+pre(xml(dat),'xml')+p('第一个成员引用 AnIn1.mag.f，FC=MX；第二个成员引用 AnIn1.q，FC=MX。顺序不可交换。GSEControl@appID 是消息标识字符串，Address/P[@type="APPID"] 为映射中的十六进制配置 1305，两者不是同一字段。MAC-Address、VLAN-ID、VLAN-PRIORITY 用于网络配置，不能证明业务目的或当前接收情况。')+figure('scd-chain','SCD 的 GOOSE 引用链',[(30,20,840,70,'C_M1101X / S1 / MEAS / LLN0 / GO_Gcb1','datSet=dsGOOSE1；confRev=1'),(30,140,390,80,'DataSet / FCDA 有序成员','GOGGIO1.AnIn1.mag.f [MX]、q [MX]…'),(480,140,390,80,'Communication / ConnectedAP / GSE','iedName、apName、ldInst、cbName 匹配'),(30,300,390,80,'类型引用链','LN → LNodeType → DOType → DAType'),(480,300,390,80,'接收方 Inputs / ExtRef','另行核对来源、控制块和接收定义')],[(220,90,220,140),(675,90,675,140),(220,220,220,300),(675,220,675,300)],'左边回答数据及类型，右边回答通信配置与接收引用。成功配置不等于当前通信已经完成。')),
sec('log-evidence','4. 日志配置与存储对象的区别',extract('LogControl')+p('lcbLogA 通过 datSet=dsLog1 选择告警数据集，logName=LD0 指向日志目标名称；不能把控制块名 lcbLogA、逻辑设备 inst=LD0 和日志存储实例混成同一对象。源文件 Log 元素数为 0，需在运行目录和设备资料中核对实际日志模型。logEna=true 是配置，intgPd=0 不产生周期记录；dchg=true 仍可按条件记录。')),
sec('settings-evidence','5. 定值组配置',extract('SettingControl')+p('此处提供 15 组和配置激活组 1。SelectEditSG、SetSGValues、ConfirmEditSGValues 的中间状态及结果不保存在这段 XML 中；先提交编辑，再决定是否激活，不能用 actSG 一项描述整个编辑流程。')),
sec('sv-evidence','6. 采样配置及版本差异',extract('SampledValueControl')+p('数据集前几项使用 FCD 引用。DelayTRtg、Vol1 等的具体结构要按模板和采用映射解释，不能按名字猜测样本标量布局。sampleSynchronized=true 是字段配置，非当前同步品质。此 SmvOpts 出现 dataRef=false；既有 B4 模式字段参考为 dataSet，本文保留实际摘录并标注差异，没有修改原文件。')+p('缺省 multicast/smpMod 的解释须按适用 SCL 模式。就文件统计而言，没有显式 multicast=false 的采样控制块；这不足以证明设备完全不具备 USVCB 能力。')),
sec('limits','7. 工程证据与运行证据如何衔接',table(['要回答的问题','SCD 提供','仍需核对'],[('报告为什么没有变化','成员、FC、DA 触发和控制块配置','关联、实例保留、RptEna、实际事件、接收处理'),('当前用了哪个定值组','初始 actSG、组数、属性设置','GetSGCBValues 和当前定值视图'),('GOOSE 被什么功能使用','发布成员和 ExtRef 引用线索','项目功能设计、输入处理和接受策略'),('采样是否同步','采样控制配置与字段选项','运行 SmpSynch、时源品质、时间性能'),('控制是否可执行','ctlModel 和模型类型','选择、占用、联锁、模式、健康及实际结果'),('历史能否恢复','BRCB/LCB 的模型配置','有效条目范围、缓存溢出、修订、日志保留策略')]))],
'原文第 6～20 章，与指定 SCD 实际 XML 结构逐项对照。该页例子不是标准原文例子。',[('acsi-engineering-workflows','工程核查流程'),('control-blocks-reference','控制块字段参考')])
SERVICES=['GetServerDirectory','Associate','Abort','Release','GetLogicalDeviceDirectory','GetLogicalNodeDirectory','GetAllDataValues','GetDataValues','SetDataValues','GetDataDirectory','GetDataDefinition','GetDataSetValues','SetDataSetValues','CreateDataSet','DeleteDataSet','GetDataSetDirectory','SetDataValues (Substitution)','SelectActiveSG','SelectEditSG','SetSGValues','ConfirmEditSGValues','GetSGValues','GetSGCBValues','Report (BRCB)','GetBRCBValues','SetBRCBValues','Report (URCB)','GetURCBValues','SetURCBValues','GetLCBValues','SetLCBValues','QueryLogByTime','QueryLogAfter','GetLogStatusValues','SendGOOSEMessage','GetGoReference','GetGOOSEElementNumber','GetGoCBValues','SetGoCBValues','SendGSSEMessage','GetGsReference','GetGSSEDataOffset','GetGsCBValues','SetGsCBValues','SendMSVMessage','GetMSVCBValues','SetMSVCBValues','SendUSVMessage','GetUSVCBValues','SetUSVCBValues','Select','SelectWithValue','Cancel','Operate','CommandTermination','TimeActivatedOperate','GetFile','SetFile','DeleteFile','GetFileAttributeValues']
page('acsi-engineering-workflows','时间、文件与 ACSI 工程核查','工程应用',[
sec('time','1. 时间模型与时间同步',p('第 18 章把时间语义、表示、外部时源、站内时间服务器、同步协议和需要时间的 IED 组成一个模型。ACSI 规定 UTC 语义与品质，具体对时协议由 SCSM 定义。时间服务器可与 ACSI 客户/服务器部署在同一硬件中，但它们的角色不同。')+table(['组成','功能','使用场景 / SCD 边界'],[('外部时源','提供已知准确度的时间、闰秒信息和时源纪元','不能把 GPS 纪元直接当 1970 UTC 纪元；本模型不指定全部硬件接口'),('站内时间服务器','向 IED 提供同步时间','当前可用性和时源品质需要运行证据'),('时间同步协议','使客户和服务器的时钟协同','8-1 等定义适用机制；后续工程 PTP 属于实际采用规范，不写成此 2003 基线必选'),('时标语义','纪元秒、分数和品质','TimeStamp 类型和 TimeQuality；参见公共类型'),('时标表示','映射定义字节/字段','EntryTime 与 TimeStamp 未必同编码'),('时间使用者','产生或解释事件、报告、样本和预约动作','SCD 类型及选项只说明配置，不证明当前满足性能')])+figure('clock-model','外部时间到应用判断',[(30,20,840,70,'外部时源','准确度、闰秒信息和纪元'),(30,135,840,70,'时间服务器 + 实际同步机制','由采用的 SCSM 和工程方案定义'),(30,255,390,80,'IED 本地时钟与时标','UTC 语义、分数与时间品质'),(480,255,390,80,'客户 / 订户解释','事件排序、采样协作、预约控制')],[(445,90,445,135),(220,205,220,255),(675,205,675,255),(420,295,480,295)],'对时机制、时标内容和应用接受策略共同决定时间是否可用。')+p('SOE（Sequence of Events，事件顺序记录）跨设备排序，须考虑时间准确度和失步；两个相差很小的事件不能只凭显示小数位断定真实先后。SV 协作还需样本计数、采样率和同步；预约控制 operTim 需在正确时间且仍满足动作条件，不能只证明定时器已启动。')+table(['核查点','含义','常见误读'],[('ClockFailure','时源不可靠，基线要求忽略该 TimeStamp','数值能显示就认为有效'),('ClockNotSynchronized','没有与外部 UTC 同步','本地时钟仍在走就认为已对时'),('TimeAccuracy','相对 UTC 的准确度等级','当作采样周期或 UI 小数位'),('FractionOfSecond','可表示二进制分辨率','60 ns 等于设备测时误差'),('DATA.t / TimeOfEntry / TimeOfLog','分别按数据、报告缓冲和日志语义采用','当成完全相同的时间'),('sampleSynchronized 配置','携带/采用同步信息的 XML 配置线索','当作当前 SmpSynch=true')])),
sec('files','2. FILE 类与全部文件服务',p('第 20 章 FILE 是服务器文件存储中的有序、非结构化二进制字节流，可以包含程序、数据或二者。ACSI 定义传输与存储管理，不定义所有文件内部格式，也不把传输成功等同于设备成功加载配置。COMTRADE 等扰动记录的格式另有规范。')+table(['属性','基线类型 / 存在','值域 / 功能','表现样式 / SCD'],[('FileName','VISIBLE STRING255','文件存储中的名；分层路径和命名约束按映射','教学 /records/event001.dat；不是本站路径'),('FileSize[0..1]','INT32U；0～4294967295','以八位位组计的文件长度；生成中文件无法确定时另按实现解释','教学 2048 字节；SCD 无全文件目录'),('LastModified','原表 43：TimeStamp','最近修改时间','人可读日期只是显示形式，运行属性由服务返回')])+table(['服务','Request','Response+','Response− / 用法'],[('GetFile','FileName','File-Data（八位位组串）','ServiceError；从服务器向客户获取内容'),('SetFile','FileName + File-Data','请求成功','ServiceError；从客户向服务器传内容'),('DeleteFile','FileName','请求成功','ServiceError；删除允许删除的设备文件'),('GetFileAttributeValues','适用 FileName/选择范围，按模型和映射','FileName + FileAttribute[1..n]，含长度与修改时间','ServiceError；先确认目录和属性')])+p('源表部分否定参数写 ServerError，正文说明使用 ServiceError，本页按失败服务语义说明。分段传输、句柄及线上请求可能映射成多个具体服务，不虚构“单个 ACSI 服务必等于单个 MMS 包”。')+sequence('file-flow','文件读取的概念流程',[('>','GetServerDirectory {ObjectClass=FILE}'),('<','可见文件名列表'),('>','GetFileAttributeValues {FileName}'),('<','大小和最近修改时间'),('>','GetFile {FileName}'),('<','File-Data 或 ServiceError')],'原创教学流程；本站只有静态知识，不提供设备文件上传、下载或删除操作。')+p('参考 SCD 有 63 个 IED 的 Services 含 FileHandling。它是工程能力声明，不能证明任意目录可读、任意文件可写，也不能证明采用 FTP/HTTP。将 SCD 作为文件传给设备是否可用，必须按设备明确支持的工程流程确认。')),
sec('conformance','3. 附录 A：基本、模型、服务一致性声明',p('附录 A 是规范性附录，用声明回答“设备承担什么角色、采用哪个映射、实现哪些模型与服务/选项”。M=强制、O=可选、c 条件符号依所选功能决定；可选不等于厂家可随意违反已声明功能的行为。客户端和服务器、发布方和订户应分别声明。')+table(['原表 A.1 项目','声明内容','核查意义'],[('B11 / B12','TPAA 服务器侧 / 客户侧','不能只查服务器是否支持'),('B21～B24','8-1、9-1、9-2 或其他 SCSM','固定采用版本和映射，不混用字段'),('B31 / B32','GSE 发布侧 / 订户侧','发送支持不自动等于接收支持'),('B41 / B42','SVC 发布侧 / 订户侧','分别核对采样产生与接受能力')])+table(['原表 A.2 模型项目','内容','工程核对'],[('M1～M4','LD、LN、DATA、DataSet','对象和成员能力'),('M5 / M6','Substitution / Setting group control','支持取代和定值编辑流程'),('M7','Buffered report control','序号、报告时标、原因、数据集名、数据引用、溢出、EntryID、BufTm、IntgPd、GI'),('M8','Unbuffered report control','序号、时标、原因、数据集名、数据引用、BufTm、IntgPd、GI'),('M9 / M10 / M11','Log control / Log / Control','记录规则、查询和控制行为'),('M12 / M13','GOOSE / GSSE','GOOSE 中 entryID、DataRefInc 等原附录项目按 SCSM 核对；不能虚构为当前 GOOSE 标准线上必带字段'),('M14 / M15','Multicast / Unicast SVC','样本发布方式与支持能力'),('M16 / M17','Time / File transfer','准确度与文件能力')])+p('原表 A.3 的 60 个编号如下，Report 在 BRCB/URCB 两处分别列项；取代复用 SetDataValues，不算新增服务语义。SendGOOSEMessage、SendGSSEMessage、SendMSVMessage 标记 MC；目录、管理、控制、文件和 SendUSVMessage 等采用 TP。具体 M/O/c 条件应按原附录选定角色逐项填写，不把这份服务清单当成所有设备必选表。')+table(['编号','服务名','关联形态'],[(f'S{i}',s,'MC' if i in (35,40,45) else 'TP') for i,s in enumerate(SERVICES,1)])+p('报告的子项 S24-1～3、S27-1～3 分别为 dchg/qchg/dupd。附录还要求记录内部时钟分辨率、准确度和支持的 TimeStamp 分辨率，三者分别填写。正文的 TimeSynchronisation 模型不是这 60 个编号中额外虚构的 S61。')+table(['条件','原附录意义','阅读提示'],[('c1～c5','支持 LD/LN/DATA 以及数据集、取代、报告、日志、时间等时形成模型依赖','先检查选择的上层模型，再判下层必需项'),('c6','至少支持 BRCB/URCB 中一种','报告功能不等于两种必须同时实现'),('c7','至少支持 QueryLogByTime / QueryLogAfter 中一种','日志功能不等于所有查询接口均有'),('c8 / c9','GSE 发送模型选择与 TP 可用时的控制支持条件','发布与管理服务分开'),('c10','至少支持 SendMSVMessage / SendUSVMessage 中一种','多播和单播不是共同必选')])+p('PICS 是协议实现一致性声明，MICS 是模型实现声明，PIXIT 是测试所需额外信息。SCL Services 也是工程能力线索，但不能替代这三类资料和实际设备行为验证。')),
sec('workflows','4. 从需求到证据的工程阅读流程',table(['工程目标','先读配置','再查服务与状态','结论边界'],[('读取测量','LN/DO/DA 类型、FC=MX、单位/缩放','GetDataDefinition、GetDataValues、q/t','当前值可信需品质与来源'),('接收遥信事件','DataSet、RCB、DA 和 TrgOps','关联、RCB 保留、RptEna、报告字段','当前快照和历史恢复分开'),('恢复 SOE','BRCB、EntryID 选项与修订','最近 ID、缓存范围与溢出','不能保证容量之外的历史'),('查询装置历史','LogControl 及日志目标','GetLogStatusValues、范围/增量查询','无 Log 元素时先核实运行模型'),('切换定值组','SettingControl、SG/SE 数据','激活/编辑/确认各阶段结果','编辑不等于生效'),('解释 GOOSE/SV','发布块、成员、通信参数与订阅','有效期、修订、测试、同步/连续性','地址不等于实际业务含义'),('解释控制失败','ctlModel、CO/CF、反馈对象','失败阶段、ServiceError、AddCause','不能单个错误名就认定现场故障'),('取回记录文件','FileHandling 与设备文件说明','目录、属性、GetFile 结果','传输成功不证明格式/内容有效')])+p('同一模型变更要同步检查首页/术语、控制块引用、成员顺序、类型和订阅链。离线知识库提供这些静态解释，不执行现场数据访问、抓包、发包或控制，也不替代工程校验和受控试验。')),
sec('checklist','5. 示例、版次与验证边界',p('工程摘录为所给源 SCD 的局部片段；教学流程和 SVG 为原创。真实名称用于定位，描述文本只作文件证据，不据此补出未知电气业务。未观察到某元素只表示本文件未配置/未表达，不能外推设备或标准不支持。')+table(['本次检查','可确认','不据此声称'],[('PDF OCR + 关键表图核对','版次、章节、关键类型/参数与原文定位','正式勘误和后续所有版本全集'),('XML 结构与引用追踪','统计与展示例子的模型链','源 SCD 完整 XSD 合法、设备已加载'),('本地链接与静态资源','入口、章节、术语锚点的离线组织','当前设备网络或运行状态'),('页面窄屏与表图','浏览器展示可读性','现场通信和控制通过验收')]))],
'第 18～20 章（表 42～43），附录 A 表 A.1～A.3（PDF 页 117～122）；结合源 SCD 能力声明。',[('standard-part-7-2','回到主章'),('scd-acsi-evidence','工程证据'),('acsi-services','服务全表')])
# Keep legacy index IDs stable and enrich entries before the home search script runs.
existing_ids={'SCL':'scl','FCDA':'fcda','FC':'fc','DAType':'datype','CDC':'cdc','ACSI':'acsi','FCD':'fcd','BRCB':'part71-brcb','URCB':'part71-urcb','LCB':'part71-lcb','dchg':'trigger-dchg','qchg':'trigger-qchg','dupd':'trigger-dupd'}
entries=[]
for a,b,c,d,e,f,z in ABBR:
 entries.append({'id':existing_ids.get(a,'acsi72-'+a.lower().replace('-','_')),'zh':a+'（'+c+'）','en':b,'aliases':[a,c,b],'category':'ACSI 类型与服务','level':d,'summary':e,'related':['acsi','fc','fcda'],'href':'chapters/'+f+'.html#'+z})
for f,t,g in pages:entries.append({'id':'chapter-'+f,'zh':t,'en':'IEC 61850-7-2 ACSI guide','aliases':[g,'第7-2部分','7-2','ACSI'],'category':g,'level':'第 7-2 部分关联专题','summary':'早期标准基线、属性与服务、参考 SCD 和工程阅读边界。','related':['acsi','scd'],'href':'chapters/'+f+'.html'})
s='/* 第 7-2 部分增补；更新既有 ID，保持旧词条引用有效。 */\n(function () {\n  const additions = '+json.dumps(entries,ensure_ascii=False,indent=2)+';\n  const terms = window.IEC61850_TERMS;\n  for (const entry of additions) {\n    const old = terms.find(term => term.id === entry.id);\n    if (old) {\n      entry.aliases = [...new Set([...old.aliases, old.zh, ...entry.aliases])];\n      entry.related = [...new Set([...old.related, ...entry.related])].filter(id => id !== entry.id);\n      Object.assign(old, entry);\n    } else {\n      entry.related = entry.related.filter(id => id !== entry.id);\n      terms.push(entry);\n    }\n  }\n}());\n'
(OUT/'data/part72-terms.js').write_text(s,encoding='utf-8')
# Correct one confirmed baseline type in the older companion page.
f=OUT/'chapters/control-blocks-reference.html';s=f.read_text(encoding='utf-8');s=s.replace('CnfEdit BOOLEAN；LActTm EntryTime','CnfEdit BOOLEAN；LActTm TimeStamp（所给 7-2 表 22）');f.write_text(s,encoding='utf-8')
print('Generated',len(pages),'pages and',len(entries),'term enrichments')
